Use safe versions of comparison operators.
dealii/dealii pull request #10900
Opened 2020-09-09 18:21 UTC by bangerth

I've used Steve McConnell's "Code Complete" as my go-to solution for all questions of good programming practice and have found it to be an excellent resource. It agrees with my general philosophy on programming in nearly all aspects.

So I was intrigued by a section on p. 442 that "In C++, consider creating preprocessor macro substitutions for &&, ||, and ==". Reading through the section, I find that that makes a whole lot of sense to me, and that we should do this in deal.II as well. McConnell suggests using `AND`, `OR`, and `EQUALS` for these macros, but that is not properly namespaced. So I chose `DEAL_II_AND`, `DEAL_II_OR`, and `DEAL_II_EQUALS`.

OK to merge?

2020-09-09 18:21 UTC, bangerth commented
/rebuild

2020-09-09 18:43 UTC, masterleinad commented on include/deal.II/algorithms/general_data_storage.h
> +                              Arg DEAL_II_AND argument,
This is just not a comparison and for me also the rest is so much less readable.

2020-09-09 19:03 UTC, peterrum commented
I don't like this change.

2020-09-09 20:12 UTC, marcfehling commented
While working with python which allows comparison operators like `and`, `or`, `not`, `is` from scratch, I must say that I tend to prefer the written-out variants over the symbol ones.

However, I feel like the `DEAL_II_` prefix makes it way harder to read. I would suggest to get rid of them and accept that they're not properly namespaced...

Further, I am not sure if other (newcomer?) C++ programmers will be irritated by these macros, and if we even scare them off.

2020-09-09 20:29 UTC, drwells commented
I think we decided long ago that the C operators were preferable even to the C++ `and`, `or`, etc.

Your mass substitution also includes every single move constructor - writing this PR in such a way that we only have logical operators and not ref-refs will be a herculean undertaking.

Please, lets not do this. Lets not make deal.II look like the old bash source with its pseudo-pascal.

2020-09-09 20:36 UTC, masterleinad requested changes
Everyone so far is against this.

2020-09-09 20:59 UTC, bangerth commented
Oof, y'all are no fun :-) I guess I should have reserved this patch for in 6 months and 21 days ;-)

2020-09-09 21:00 UTC, masterleinad commented
> Oof, y'all are no fun :-) I guess I should have reserved this patch for in 6 months and 21 days ;-)

Absolutely! :slightly_smiling_face:

2020-09-10 06:20 UTC, peterrum commented
Let's close this for now. If there should be a time when we really want to abandon the beautiful C-operators, then let's rather consider switching the programming language completely.

2020-09-10 06:20 UTC, closed without merging

2020-09-15 23:46 UTC, bangerth commented
On 9/10/20 12:20 AM, Peter Munch wrote:
> If there should be a time when we really want to abandon the beautiful 
> C-operators, then let's rather consider switching the programming language 
> completely.

I propose Ada! (Or maybe Haskell? I've grown to like functional programming 
more over time!) :-)