Update documentation of MatrixTools::apply_boundary_values().
dealii/dealii pull request #10978
Opened 2020-09-28 22:51 UTC by bangerth

Following the discussion on the mailing list.

2020-10-02 07:15 UTC, kronbichler commented on include/deal.II/numerics/matrix_tools.h
> + * specifically: "strong" boundary condition). To actually do this, the
```suggestion
 * specifically: "strong" boundary conditions). To actually do this, the
```

2020-10-02 07:15 UTC, kronbichler commented on include/deal.II/numerics/matrix_tools.h
> + * ConstraintMatrix::copy_local_to_global() performs the same process as part of
```suggestion
 * AffineConstraints::distribute_local_to_global() performs the same process as part of
```

2020-10-10 21:41 UTC, bangerth commented
Thanks, @kronbichler . Adjusted as requested!

2020-10-10 21:42 UTC, bangerth commented
Well, actually no -- the airport wireless allows for web traffic but not my git connection. Will get back to you once it's updated.

2020-10-11 20:37 UTC, bangerth commented
OK, now for real!

2020-10-15 19:04 UTC, drwells requested changes
I have a few minor suggestions but overall this looks good.

2020-10-15 19:04 UTC, drwells commented on include/deal.II/numerics/matrix_tools.h
> + * system itself. A third way, using the
```suggestion
 * system itself. A third way, using
```

2020-10-15 19:04 UTC, drwells commented on include/deal.II/numerics/matrix_tools.h
> + * AffineConstraints::copy_local_to_global() performs the same process as part
```suggestion
 * AffineConstraints::copy_local_to_global(), performs the same process as part
```

2020-10-15 19:04 UTC, drwells commented on include/deal.II/numerics/matrix_tools.h
> +   * works for block sparse matrices and block vectors
```suggestion
   * works for block sparse matrices and block vectors.
```

2020-10-20 03:09 UTC, bangerth commented
@drwells Updated as requested. Thanks for the careful reading!

2020-10-20 03:09 UTC, bangerth commented
@drwells Updated as requested. Thanks for the careful reading!

2020-10-20 13:47 UTC, drwells approved these changes

2020-10-20 13:47 UTC, merged