Document reference cells in simplex module page
dealii/dealii pull request #11095
Opened 2020-10-24 08:16 UTC by peterrum

Closes #11084.

The output would look like this:

![Screenshot from 2020-10-24 10-12-12](https://user-images.githubusercontent.com/15707929/97075502-a5e4eb00-15e1-11eb-807e-0e2247baee90.png)

The 3D pictures need to be so large else you cannot recognize the numbers in the small circles.

2020-10-24 12:02 UTC, drwells requested changes
We might want to replace these with ASCII later but we need to publish the numberings somewhere now so this looks good to me.

2020-10-24 12:02 UTC, drwells commented on doc/doxygen/headers/simplex.h
> + *       <img src="https://user-images.githubusercontent.com/15707929/97070787-63b8ab00-15db-11eb-9e4b-b254b110bf18.png"
We need to host our own images for the offline documentation to work correctly.

2020-10-24 13:21 UTC, drwells commented
Did we ever agree on what kind of images should be put in `doc/doxygen/images` and which should go on the web site? I think it's fine for small things like this to be in the library (we definitely have test output files larger than 15 kb).

2020-10-26 14:21 UTC, drwells commented
The largest test output files are something like 5 MB each so I don't think its a big deal if we put images like this in the repository itself. Can we just do that? If anyone objects let's talk about it.

2020-11-21 19:33 UTC, peterrum commented
@drwells I have added the pictures!

2020-11-21 21:09 UTC, drwells approved these changes

2020-11-21 21:10 UTC, merged