Updated documentation to avoid hp::DoFHandler.
dealii/dealii pull request #11214
Opened 2020-11-20 01:22 UTC by marcfehling

While browsing through the documentation, I've found duplicates of functions in header files that I removed.

So although this PR effectively just changes the documentation, please run the testsuite to be sure nothing breaks.

2020-11-20 01:29 UTC, marcfehling commented
Part of #10333.

2020-11-21 17:40 UTC, drwells requested changes
Nice! I caught a few minor things (mostly with commas).

2020-11-21 17:40 UTC, drwells commented on include/deal.II/dofs/dof_tools.h
> +   * The ::DoFHandler was not initialized with a finite element. Please call
```suggestion
   * The DoFHandler was not initialized with a finite element. Please call
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/distributed/solution_transfer.h
> +       *   points to the triangulation before the refinement in question
```suggestion
       *   points to the Triangulation before the refinement in question
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/distributed/solution_transfer.h
> +     * processed with its correpsonding `future_fe_index`. Further, if
```suggestion
     * processed with its corresponding `future_fe_index`. Further, if
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/intergrid_map.h
> + * equally well be Triangulation, or PersistentTriangulation).
```suggestion
 * equally well be Triangulation or PersistentTriangulation).
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * Given two meshes (i.e. objects of type Triangulation, or DoFHandler) that
```suggestion
   * Given two meshes (i.e. objects of type Triangulation or DoFHandler) that
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * @param mesh A mesh (i.e. objects of type Triangulation, or DoFHandler).
```suggestion
   * @param mesh A mesh (i.e. objects of type Triangulation or DoFHandler).
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * @param mesh A mesh (i.e. objects of type Triangulation, or DoFHandler).
```suggestion
   * @param mesh A mesh (i.e. objects of type Triangulation or DoFHandler).
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * @param[in] mesh A mesh (i.e. objects of type Triangulation, or DoFHandler).
```suggestion
   * @param[in] mesh A mesh (i.e. objects of type Triangulation or DoFHandler).
```

2020-11-21 17:40 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * @param[in] mesh A mesh (i.e. objects of type Triangulation, or DoFHandler).
```suggestion
   * @param[in] mesh A mesh (i.e. objects of type Triangulation or DoFHandler).
```

2020-11-21 17:54 UTC, drwells approved these changes

2020-11-21 17:55 UTC, drwells commented
/rebuild

2020-11-22 10:24 UTC, peterrum approved these changes

2020-11-22 10:24 UTC, merged