Consense in using hp concatenation symbols.
dealii/dealii pull request #11216
Opened 2020-11-20 01:48 UTC by marcfehling

Blocked by #11214.

Part of #10333.

---

In the deal.II hp paper and the the original hp papers by Babuska and Suri, any term regarding hp adaptation was written in the following style with a space in between:
```
hp adaptation, h refinement, ...
```

In more recent papers, you find a hyphen for concatenation. (I also used this stye in my dissertation.)
```
hp-adaptation, h-refinement, ...
```

Right now in the library, we use both versions inconsistently. This PR is an attempt to adapt to the **original** nomenclature.

---

This is an entirely cosmetic change to the documentation, and there might be other opinions on which version to choose.

Especially for @bangerth: What are your thoughts on that?

2020-11-22 10:40 UTC, peterrum reviewed
> h adaptivity -> h adaptivity

I am in favor of `h-adaptivity`,  `p-adaptivity`, and `hp-adaptivity` as it is also frequently used in the multigrid context.

> active_fe_indices -> active fe indices

I don't have any particular opinion here. But shouldn't fe than written in all caps?

2020-12-01 05:10 UTC, bangerth commented
We probably need a native speaker here. @drwells @jppelteret ?

I *think* that the grammatically proper resolution would probably be to use the following:
* "h-adaptive refinement" (in the same style as "truck-related accidents" -- it's a compound adjective: https://www.gingersoftware.com/content/grammar-rules/adjectives/compound-adjectives/)
* "h adaptivity", where "h" is an adjective to the noun "adaptivity".

Same of course for "p-adaptive", "hp-adaptive", "p adaptivity", "hp adaptivity".

2020-12-01 05:14 UTC, bangerth requested changes

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/distributed/solution_transfer.h
> +     * processed with its corresponding `future fe index`. Further, if
You're referencing a technical term here, which is used in function and variable names. I think it should be written with underscores if you mark it up with the backticks. If you want spaces, remove the backticks.

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/distributed/solution_transfer.h
> +     * processed with its corresponding `future fe index`. Further, if
Same everywhere else

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/distributed/solution_transfer.h
> +     * store the active fe indices in an additional step. A code snippet
this seems correct then.

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/dofs/dof_accessor.templates.h
> +         ExcMessage("You can only query future fe index information on cells "
Here and elsewhere, I wonder whether if you already remove the underscore, we should improve readability by saying "(active|future) FE index" (with fe capitalized). This makes it clear that this part of the expression is supposed to be an abbreviation.

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/dofs/dof_handler.h
> + * <h3>hp adaptive finite element methods</h3>
I think it should stay here

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/fe/fe_enriched.h
> +   * and h adaptive refinement. For a given cell, the material id is used
and here

2020-12-01 05:14 UTC, bangerth commented on include/deal.II/fe/fe_series.h
> + * on h or p adaptive refinement strategy.
and here

and probably a few other places

2020-12-01 21:23 UTC, drwells commented
Both work but I am in favor of `hp-adaptivity` et al.

2020-12-08 21:55 UTC, marcfehling commented
After thinking about it, I decided to use the `hp-` variant in any possible case. This also involves the following which look a bit odd, but I prefer them over the alternative.
```
hp-finite element or hp-FEM
hp-DoFHandlers and non-hp-DoFHandlers
hp-classes and non-hp-classes
```

Further, I changed any standalone `fe` in the documentation to `FE`.

2020-12-08 22:48 UTC, marcfehling commented
For completion: The search and replace scripts I used to prepare this PR.
```
perl -p -i -e 's/(^\s*(\/\/|\*).*\W)(?<!\@ref )(?<!\@defgroup )(?<!\@ingroup )(?<!namespace )hp( |$)/\1hp-/g' `find ./ -type f`
perl -p -i -e 's/(^\s*(\/\/|\*).*\W)(?<!\.)h( |$)/\1h-/g' `find ./ -type f`
perl -p -i -e 's/(^\s*(\/\/|\*).*\W)(?<!@)p( |$)/\1p-/g' `find ./ -type f`

perl -p -i -e 's/(^\s*(\/\/|\*).*\W)fe( |$)/\1FE\2/g' `find ./ -type f`
```

`GNU sed` does not allow lookahead/lookbehind, so I had to use pearl here.

2020-12-10 22:05 UTC, jppelteret commented
> Both work but I am in favor of hp-adaptivity et al.

I'm super late to the party, but I also lean towards hyphenating all of

> h-adaptivity, p-adaptivity, and hp-adaptivity

Irrespective of whether of not its grammatically correct, its certainly commonplace amongst the scientific literature (and [Wikipedia page](https://en.wikipedia.org/wiki/Hp-FEM), if that means anything at all). So I don't think that we'd be "wrong" in adopting this notation. 

> "h adaptivity", where "h" is an adjective to the noun "adaptivity".

@bangerth I can't think of any rebuttal to this because it seems totally correct, but I need some eye floss after reading this :-D I've always found it odd to see some hovering "h" or "p" or "hp" in a sentence, but that is of course indicative of my personal taste.

2020-12-16 03:20 UTC, marcfehling commented
Ready for review.

Please also run the testsuite on this PR as some exception messages have also changed, which are caught in a few tests.

2020-12-18 05:03 UTC, masterleinad commented
/rebuild

2020-12-18 20:10 UTC, bangerth approved these changes

2020-12-18 22:18 UTC, merged