Introduce QGaussWedge
dealii/dealii pull request #11268
Opened 2020-11-28 08:32 UTC by peterrum

2020-12-01 16:38 UTC, drwells requested changes
Two small things

2020-12-01 16:38 UTC, drwells commented on include/deal.II/simplex/quadrature_lib.h
> +    explicit QGaussWedge(const unsigned int n_points);
```suggestion
    explicit QGaussWedge(const unsigned int n_points_1D);
```

2020-12-01 16:38 UTC, drwells commented on include/deal.II/simplex/quadrature_lib.h
> +     * degree to be integrated exactly.For details, see the comments of
```suggestion
     * degree to be integrated exactly. For details, see the comments of
```

2020-12-02 11:44 UTC, peterrum commented
@drwells Thanks for the review. I have made the changes.

2020-12-02 11:54 UTC, peterrum commented
/rebuild

2020-12-02 15:05 UTC, drwells approved these changes

2020-12-02 15:05 UTC, merged