Use boost implementation of legendre polynomials instead of gsl.
dealii/dealii pull request #11283
Opened 2020-12-01 01:48 UTC by marcfehling

Noticed in #11254.

Instead of using the boost variant directly, we could also introduce a `legendre` function in the `std_cxx17` namespace which uses the boost implementation. This way we could remind ourselves of using the CXX17 function once we move to the more recent standard. I don't expect the results to be different, as they are also not different between boost and gsl.

What is your preference?

2020-12-01 02:24 UTC, masterleinad commented
We already use `std::cyl_bessel_j*`. I don't see a reason not to do the same for the Legendre polynomials.

2020-12-01 02:29 UTC, bangerth commented
Ah, yes, the hive mind works! I had forgotten about `std::cyl_bessel_j`.

@marcfehling -- can you add the same kind of approach to `include/deal.II/base/std_cxx17/cmath.h` and use that here?

2020-12-01 03:33 UTC, marcfehling commented
The `std` functions use the type `unsigned int` for the index parameter, while the `boost` implementation uses `int`.

I provided them as functions with a `static_cast` instead of function pointers like with the Bessel functions. What do you think?

2020-12-01 04:16 UTC, marcfehling commented
Blocked by #11286 as we include `cmath.h` twice now :-)

2020-12-01 04:20 UTC, marcfehling commented
Grr, this issue also affects the double definition of the Legendre polynomials.
```
 /usr/bin/ld.gold: error: base/CMakeFiles/obj_base_release.dir/function_lib.cc.o: multiple definition of 'dealii::std_cxx17::legendre(unsigned int, double)'
```

I'll think of a fix.

2020-12-01 04:36 UTC, bangerth commented
If you implement these as functions, then `constexpr` is the wrong approach. You want `inline` :-)

(As a matter of fact, we also want `inline` variables in #11286, but that's a C++17 feature...)

2020-12-01 04:44 UTC, marcfehling commented
> If you implement these as functions, then `constexpr` is the wrong approach. You want `inline` :-)

Ah, since those are actual function and not just function pointers. I get it now :-)

2020-12-01 04:59 UTC, bangerth approved these changes

2020-12-01 04:59 UTC, bangerth commented
Can you squash the last few commits?

2020-12-01 05:00 UTC, bangerth commented
Blocked by #11286. Otherwise ok to merge once squashed.

2020-12-01 05:00 UTC, bangerth commented
/rebuild

2020-12-01 06:22 UTC, marcfehling commented
Hmm it looks like the CI doesn't like the `constexpr` flag for the function pointers, as the linker complains particularly about the Bessel functions.
```
/usr/bin/ld.gold: error: base/CMakeFiles/obj_base_release.dir/function_lib.cc.o: multiple definition of 'dealii::std_cxx17::cyl_bessel_jl'
/usr/bin/ld.gold: fe/CMakeFiles/obj_fe_release.dir/fe_series_legendre.cc.o: previous definition here
/usr/bin/ld.gold: error: base/CMakeFiles/obj_base_release.dir/function_lib.cc.o: multiple definition of 'dealii::std_cxx17::cyl_bessel_jf'
/usr/bin/ld.gold: fe/CMakeFiles/obj_fe_release.dir/fe_series_legendre.cc.o: previous definition here
/usr/bin/ld.gold: error: base/CMakeFiles/obj_base_release.dir/function_lib.cc.o: multiple definition of 'dealii::std_cxx17::cyl_bessel_j'
/usr/bin/ld.gold: fe/CMakeFiles/obj_fe_release.dir/fe_series_legendre.cc.o: previous definition here
```

Shall we turn the function pointers to wrapper functions as well? Hmm, or maybe it would help to flag them static.

2020-12-01 14:54 UTC, bangerth commented
Hm. Can you rebase to master and see again what happens?

2020-12-01 16:27 UTC, masterleinad reviewed
We should use a common style here. I would be fine with `inline` functions.

2020-12-01 16:29 UTC, masterleinad requested changes
We should use a common style here. I would be fine with inline functions.

2020-12-01 17:55 UTC, marcfehling commented
The CI complains about the `constexpr` and `inline` flags for the function pointers. It works with a `static` flag or when turning them to wrapper functions.

I comply to @masterleinad's suggestion to use the `inline` flag in combination with wrapper functions.

2020-12-01 18:09 UTC, masterleinad approved these changes

2020-12-02 05:06 UTC, bangerth commented
You'll need to run the indentation script.

2020-12-02 06:19 UTC, marcfehling commented
Even the indentation script got stuck. I need to rebase now anyways. Give me a sec

2020-12-02 08:26 UTC, marcfehling commented
I've changed the parameter names to be in accordance with this [`cmath.h` reference](https://en.cppreference.com/w/cpp/header/cmath).

Ready for merge.

2020-12-02 15:30 UTC, bangerth approved these changes

2020-12-02 15:30 UTC, merged