Implement FE_WedgeDGP and FE_PyramidDGP
dealii/dealii pull request #11405
Opened 2020-12-20 09:58 UTC by peterrum

... and introduce the base classes `FE_Wedge` and `FE_Pyramid`.

2020-12-22 18:20 UTC, drwells requested changes

2020-12-22 18:20 UTC, drwells commented on include/deal.II/simplex/fe_lib.h
> +   * the finite element space of discontinuous, piecewise polynomials of
```suggestion
   * the finite element space of continuous, piecewise polynomials of
```

2020-12-22 18:20 UTC, drwells commented on include/deal.II/simplex/fe_lib.h
> +   * the finite element space of continuous, piecewise polynomials of
```suggestion
   * the finite element space of discontinuous, piecewise polynomials of
```

2020-12-22 18:20 UTC, drwells commented on include/deal.II/fe/fe_base.h
> +  internal::GenericDoFsPerObject
Could we document this function?

2020-12-22 18:37 UTC, peterrum commented
@drwells Done!

2020-12-22 18:45 UTC, drwells approved these changes

2020-12-22 18:45 UTC, drwells commented
/rebuild

2020-12-23 16:00 UTC, peterrum commented
/rebuild

2020-12-23 17:45 UTC, merged