Fix: single test output dir per test
dealii/dealii pull request #11567
Opened 2021-01-16 10:08 UTC by peterrum

The side effect of #11427 was that two folders per test has been create: one with the category as prefix, one without it. This PR fixes this.

2021-01-16 12:51 UTC, drwells requested changes
Looks good aside from the minor style suggestion.

2021-01-16 12:51 UTC, drwells commented on cmake/macros/macro_deal_ii_add_test.cmake
> +        set_target_properties(${_target} PROPERTIES OUTPUT_NAME ${_target_short})
```suggestion
        SET_TARGET_PROPERTIES(${_target} PROPERTIES OUTPUT_NAME ${_target_short})
```

2021-01-16 12:52 UTC, drwells commented
Thanks for checking this out!

2021-01-16 20:02 UTC, peterrum commented on cmake/macros/macro_deal_ii_add_test.cmake
> +        set_target_properties(${_target} PROPERTIES OUTPUT_NAME ${_target_short})
OK. I have changed this!

2021-01-16 20:20 UTC, drwells approved these changes

2021-01-16 20:21 UTC, drwells commented
/rebuild

2021-01-18 08:31 UTC, kronbichler approved these changes

2021-01-18 08:31 UTC, merged

2021-01-18 09:03 UTC, bangerth commented
Ah, this also explains why I recently had trouble finding the executable for tests as they were no longer located in the usual directory. I had to start searching for them. Thanks for fixing this again.