Enable MGTwoLevelTransfer::reinit_geometric_transfer for FECollections
dealii/dealii pull request #11578
Opened 2021-01-18 18:19 UTC by peterrum

2021-02-02 20:28 UTC, peterrum commented
/rebuild

2021-02-08 05:13 UTC, marcfehling requested changes
The assertions state that this is only available if all elements in a `FECollection` are identical, and all cells on each `DoFHandler` have the same active FE index. Right?

2021-02-08 05:13 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +
```suggestion

      // make sure that no hp is used on either coarse or fine dofhandler respectively
```

2021-02-08 09:50 UTC, peterrum commented
Thanks for the review.  I have made the changes. Regading:

> The assertions state that this is only available if all elements in a FECollection are identical

No.

> and all cells on each DoFHandler have the same active FE index. Right?

Yes.

2021-02-09 09:30 UTC, kronbichler approved these changes
Looks good to me apart from a typo in a variable name.

2021-02-09 09:30 UTC, kronbichler commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +      std::array<unsigned int, 2> min_active_fe_indicices = {
```suggestion
      std::array<unsigned int, 2> min_active_fe_indices = {
```
(and the same for `max_fe_indices`).

2021-02-09 09:43 UTC, peterrum commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +      std::array<unsigned int, 2> min_active_fe_indicices = {
Fixed.

2021-02-09 13:53 UTC, merged