Python wrappers for simplex and mixed meshes
dealii/dealii pull request #11582
Opened 2021-01-18 20:47 UTC by agrayver

Now you can query geometry and reference cell type from within python. Additionally, adds a wrapper for `GridGenerator::convert_hypercube_to_simplex_mesh`.

Related to #11508

2021-01-18 20:51 UTC, peterrum reviewed
Looks good to me! Thanks a lot!

2021-01-18 20:51 UTC, agrayver commented
An example...

![Firefox_Screenshot_2021-01-18T20-50-38 655Z](https://user-images.githubusercontent.com/8438035/104961757-40817a00-59d7-11eb-8ff1-a1401871254b.png)

2021-01-18 20:51 UTC, peterrum commented
FYI @eliasstudiert

2021-01-20 01:44 UTC, Rombur reviewed
The code looks fine but it would be nice to have a test.

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/include/reference_cell_wrapper.h
> +// Copyright (C) 2016 - 2020 by the deal.II authors
Wrong years

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/cell_accessor_wrapper.cc
> +
Need more blank lines

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/export_reference_cell.cc
> +// Copyright (C) 2016 - 2020 by the deal.II authors
Wrong years.

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/reference_cell_wrapper.cc
> +// Copyright (C) 2016 - 2020 by the deal.II authors
Years

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/reference_cell_wrapper.cc
> +
Not enough blank space between functions. Same below.

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/triangulation_wrapper.cc
> +  void
Not enough blank lines

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/tria_accessor_wrapper.cc
> +      return internal::tria_accessor_cast<1, 2, 3>(tria_accessor)->n_vertices();
Why don't we have `internal::tria_accessor_cast<2, 2, 3>(tria_accessor)->n_vertices();`

2021-01-20 01:44 UTC, Rombur commented on contrib/python-bindings/source/tria_accessor_wrapper.cc
> +      return internal::tria_accessor_cast<2, 3, 3>(tria_accessor)->n_vertices();
Why don't we have `internal::tria_accessor_cast<1, 3, 3>(tria_accessor)->n_vertices();` and `internal::tria_accessor_cast<3, 3, 3>(tria_accessor)->n_vertices();`?

2021-01-20 11:21 UTC, agrayver commented
@Rombur addressed your comments, thanks.

2021-01-20 22:02 UTC, Rombur requested changes
I have a few more comments. I should have been paying more attention the first time around. Sorry.

2021-01-20 22:02 UTC, Rombur commented on contrib/python-bindings/source/export_reference_cell.cc
> +// Copyright (C) 2016 - 2021 by the deal.II authors
```suggestion
// Copyright (C) 2021 by the deal.II authors
```

2021-01-20 22:02 UTC, Rombur commented on contrib/python-bindings/source/reference_cell_wrapper.cc
> +// Copyright (C) 2016 - 2021 by the deal.II authors
```suggestion
// Copyright (C) 2021 by the deal.II authors
```

2021-01-21 11:29 UTC, agrayver commented
I fixed issues and added more cases. I suggest that the remaining cases are added on demand.

2021-01-22 02:11 UTC, Rombur approved these changes

2021-01-22 02:12 UTC, Rombur commented
/rebuild

2021-01-22 03:21 UTC, merged