Move a function that is not performance-critical to the .cc file.
dealii/dealii pull request #11607
Opened 2021-01-22 21:49 UTC by bangerth

In the same direction as started in #11544.

/rebuild

2021-01-22 22:11 UTC, drwells requested changes
One minor thing.

2021-01-22 22:11 UTC, drwells commented on source/grid/reference_cell.cc
> +   */
```suggestion
```
Could we get rid of the documentation? It looks out of place in a source file.

2021-01-22 22:28 UTC, peterrum approved these changes

2021-01-23 23:26 UTC, bangerth commented
@drwells -- yes, good idea! So done.

2021-01-24 01:21 UTC, drwells approved these changes

2021-01-24 01:21 UTC, merged