Add utility functions to create polynomial coarsening sequences
dealii/dealii pull request #11706
Opened 2021-02-06 21:14 UTC by peterrum

2021-02-08 02:32 UTC, marcfehling approved these changes

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.h
> +   * TODO.
You'll specify this comment and some other parts in #11699. So this PR is blocked by #11699?

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> -                    cell_id_translator.to_cell_id(cell_id)),
CellId::to_cell is deprecated. I think you can safely keep the old code here and in all the other occasions.

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> -              *tria_dst.create_cell_iterator(cell_id), &dof_handler_dst);
Same here.

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> -                   cell->id()),
Same here.

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> -                   cell->id()),
Same here.

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +    degrees.push_back(max_degree);
```suggestion
    std::vector<unsigned int> degrees = {max_degree};
```

2021-02-08 02:32 UTC, marcfehling commented on include/deal.II/multigrid/mg_transfer_global_coarsening.h
> +   * determine the full sequence of polynomial degrees.
```suggestion
   * determine the full sequence of polynomial degrees in ascending order.
```

2021-02-08 10:15 UTC, peterrum commented
@marcfehling Thanks for the review. I have removed the accidental copy-and-paste stuff.

2021-02-09 06:39 UTC, kronbichler requested changes

2021-02-09 06:39 UTC, kronbichler commented on include/deal.II/multigrid/mg_transfer_global_coarsening.h
> +     * Half polynomial degree. E.g., for degree=7 following sequence would
```suggestion
     * Half polynomial degree by integer division. For example, for degree=7 the following sequence would be obtained:
```

2021-02-09 06:39 UTC, kronbichler commented on include/deal.II/multigrid/mg_transfer_global_coarsening.h
> +   * determine the full sequence of polynomial degrees in ascending order.
```suggestion
   * determine the full sequence of polynomial degrees, sorted in ascending order.
```

2021-02-09 06:39 UTC, kronbichler commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +      }
Why not simply
```suggestion
    unsigned int previous_fe_degree = max_degree;
    while (degrees.back() > 1)
      degrees.push_back(create_next_polynomial_coarsening_degree(degrees.back(),
                                                                 p_sequence));
```

2021-02-09 08:11 UTC, peterrum commented on include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
> +      }
Much better!

2021-02-09 08:11 UTC, peterrum commented
@kronbichler Thanks for the review. I have addressed the comments.

2021-02-09 08:38 UTC, kronbichler approved these changes

2021-02-09 08:40 UTC, kronbichler commented
/rebuild

2021-02-09 11:53 UTC, merged