Added Utilities::MPI::logical_or().
dealii/dealii pull request #11850
Opened 2021-03-05 01:30 UTC by marcfehling

New function for collective _logical or_ operations. Will be used in a follow-up PR.

Can not be used on `std::vector<bool>` since its specialization may not store its elements in a contiguous array.

2021-03-05 07:48 UTC, peterrum approved these changes
Why did you not simply use `Utilities::MPI::max()` which is equivalent?

2021-03-05 20:30 UTC, bangerth requested changes
What is `MPI_LOR`? A bitwise `or` operation? I'm not familiar with the term "logical or", and if I'm not, then it might be useful to explain it in the documentation. That would also cover the question of what kind of template arguments `T` this function is useful for.

2021-03-06 04:55 UTC, marcfehling commented
> Why did you not simply use `Utilities::MPI::max()` which is equivalent?

This would have worked as well...
In retrospective for my use case, I would only need to provide an overload of the `mpi_type_id` function for the `bool` data type.

2021-03-06 04:58 UTC, marcfehling commented
> What is `MPI_LOR`? A bitwise `or` operation? I'm not familiar with the term "logical or", and if I'm not, then it might be useful to explain it in the documentation. That would also cover the question of what kind of template arguments `T` this function is useful for.

`MPI_LOR` is the _logical or_ operation `||`. `MPI_BOR` is the _bitwise or_ operation `|`.
I'll be more elaborate, and also on how different data types `T` will be treated.

2021-03-06 21:31 UTC, bangerth approved these changes

2021-03-06 21:32 UTC, bangerth commented
/rebuild

2021-03-06 21:34 UTC, bangerth commented
Right now, you allow any data type `T` to be passed, but what does MPI do if that data type is, for example, `std::complex<double>`? I would suspect that MPI has some sort of restrictions on what that could be, and it would probably be useful to encode those into a `static_assert` in the one function you route everything through (or all of them). Maybe something like
```
  static_assert (std::is_convertible<T,bool>::value, "...");
```
?

2021-03-07 02:17 UTC, marcfehling commented
> Right now, you allow any data type `T` to be passed, but what does MPI do if that data type is, for example, `std::complex<double>`? I would suspect that MPI has some sort of restrictions on what that could be, and it would probably be useful to encode those into a `static_assert` in the one function you route everything through (or all of them). Maybe something like
> 
> ```
>   static_assert (std::is_convertible<T,bool>::value, "...");
> ```
> 
> ?

According to the mpi documentation, the `MPI_LOR` operation requires an `integral` type. I will check for that instead.

2021-03-07 20:13 UTC, bangerth approved these changes
Much appreciated, in particular the multitude of tests!

2021-03-07 20:13 UTC, merged