Add nearest predicate to ArborX wrapper
dealii/dealii pull request #11963
Opened 2021-03-25 13:09 UTC by Rombur

This PR adds a nearest neighbor predicate to ArborX wrappers. While adding the predicate, I realized that the current design was not extensible and that the names were not great. I have created base classes that contains most of the implementation and added `Predicate` to the name of the classes since that's what they are. The classes were introduces a month ago so there is no backward compatibility problem.

2021-03-26 13:13 UTC, jppelteret requested changes
A couple of superficial comments, but otherwise LGTM!

2021-03-26 13:13 UTC, jppelteret commented on doc/news/changes/minor/20210319Turcksin
> +allows to find the n closest bounding boxes or points to any given bounding
```suggestion
allows to find the `n` closest bounding boxes or points to any given bounding
```

2021-03-26 13:13 UTC, jppelteret commented on include/deal.II/arborx/access_traits.h
> +     * Constructor. @p bounding_boes is a list of bounding boxes used by the
```suggestion
     * Constructor. @p bounding_boxes is a list of bounding boxes used by the
```

2021-03-26 13:13 UTC, jppelteret commented on include/deal.II/arborx/bvh.h
> +     * Constructor. Use a vector of Points @p points as primitives.
```suggestion
     * Constructor. Use a vector of @p points as primitives.
```

2021-03-26 18:12 UTC, Rombur commented
Done.

2021-03-26 19:52 UTC, jppelteret approved these changes
Hi @Rombur, I've found another couple of minor typos. I'm sorry that I didn't spot them earlier. Perhaps you can fix them up, and I'll approve in the mean time to minimise the inconvenience.

2021-03-26 19:52 UTC, jppelteret commented on include/deal.II/arborx/access_traits.h
> +   * which points are the nearesst to the bounding boxes/points used to build
```suggestion
   * which points are the nearest to the bounding boxes/points used to build
```

2021-03-26 19:52 UTC, jppelteret commented on include/deal.II/arborx/access_traits.h
> +     * the `i`th dealii::Point stored in @p pt_nearest
```suggestion
     * the `i`th dealii::Point stored in @p pt_nearest.
```

2021-03-26 20:10 UTC, jppelteret commented
Great, thanks a lot!

2021-03-26 20:11 UTC, jppelteret commented
/rebuild

2021-03-26 20:11 UTC, jppelteret commented
I see that @masterleinad wants to review this as well, so let's give him some time to take a look at it.

2021-03-26 20:11 UTC, masterleinad reviewed
I think the comments are phrased backward. Otherwise, this looks good to me.

2021-03-26 20:11 UTC, masterleinad commented on include/deal.II/arborx/access_traits.h
> +   *  boxes intersect the bounding boxes used to build the ArborXWrappers::BVH.
```suggestion
   *  This class is used by ArborXWrappers::BVH to determine for given bounding boxes
   *  which of the bounding boxes used to build the ArborXWrappers::BVH intersect with them.
```

2021-03-26 20:11 UTC, masterleinad commented on include/deal.II/arborx/access_traits.h
> +   * ArborXWrappers::BVH.
```suggestion
   * This class defines a predicate used by ArborXWrappers::BVH to determine
   * for given points which of the bounding boxes used to build the
   * ArborXWrappers::BVH intersect with them.
```

2021-03-26 20:11 UTC, masterleinad commented on include/deal.II/arborx/access_traits.h
> +     * for.
```suggestion
     * Constructor. @p bounding_boxes is a list of bounding boxes for which are interested in
     * knowing the @p n_nearest_neighbors nearest bounding boxes used to build the
     * ArborXWrappers::BVH.
```

2021-03-26 20:58 UTC, Rombur commented
@masterleinad You are right. Thanks. I have fixed it.

2021-03-26 22:15 UTC, masterleinad approved these changes
Looks OK to me.

2021-03-29 04:19 UTC, merged

2021-03-29 04:21 UTC, bangerth commented
There are two approvals of this PR, so I'm not going to take a third view in detail. But I do want to ask: Base classes are generally used as "interfaces" with `virtual` functions. But yours don't have virtual functions; you might want to elaborate on how derived classes are supposed to use these classes as "base classes".

(A related example is `Quadrature`, which is also a base class without virtual functions.)

2021-03-31 05:47 UTC, jppelteret commented
@bangerth's comment got me thinking... do we at least need to make the destructor for the base class `PointPredicate` virtual?

2021-03-31 13:29 UTC, masterleinad commented
I think we just want to use a base class to share code the derived classes have in common. We don't overwrite any member functions and thus they don't have to be virtual. Since none of the derived classes does anything meaningful in their destructor, having the destructor `virtual` is not crucial but maybe good practice.

2021-03-31 13:32 UTC, Rombur commented
Oh sorry, I didn't these messages. Like @masterleinad said the base class is not an interface. Because of the design of ArborX, I need two different class that have the same implementation but one of the two needs to store an extra variable. I moved all the implementation into the base class and I derived two classes but they are empty shells.

2021-03-31 13:33 UTC, masterleinad commented
That being said we could just use `private` or `protected` inheritance to make sure that we don't use them in a polymorphic context.

2021-03-31 13:35 UTC, Rombur commented
@masterleinad that's a good idea