Fix typo in GridTools::collect_periodic_faces
dealii/dealii pull request #11978
Opened 2021-03-29 16:13 UTC by masterleinad

We don't use "dimension" anywhere in the function signature and this should really be the same as "direction".

2021-03-29 17:48 UTC, drwells requested changes
We need to fix one more.

2021-03-29 17:48 UTC, drwells commented on include/deal.II/grid/grid_tools.h
>     * index <code>2*dimension+1</code> and boundary indicator @p b_id. Faces
```suggestion
   * index <code>2*direction+1</code> and boundary indicator @p b_id. Faces
```

2021-03-29 19:11 UTC, masterleinad commented on include/deal.II/grid/grid_tools.h
>     * index <code>2*dimension+1</code> and boundary indicator @p b_id. Faces
Thanks! Fixed via force-push.

2021-03-29 19:51 UTC, drwells approved these changes

2021-03-30 01:32 UTC, Rombur approved these changes

2021-03-30 01:32 UTC, merged