Improve error messages during configuration.
dealii/dealii pull request #12027
Opened 2021-04-08 17:45 UTC by bangerth

We print an error message in our wrappers to the `FIND_` macros that shows a string representation of arguments to the macro. But cmake has a habit of clobbering these arguments and overwriting with values that are not useful to output. We should output the original set of arguments, so let's save them.

Example
```
-- SUNDIALS_CONFIG_H not found! Call:
--     FIND_FILE(SUNDIALS_CONFIG_H NAMES sundials_config.h HINTS SUNDIALS_INCLUDE_DIR-NOTFOUND/sundials)
```
Note the appearance of the `SUNDIALS_INCLUDE_DIR-NOTFOUND` text.

/rebuild

2021-04-13 14:50 UTC, drwells requested changes
I checked that this fixes the output issue - nice work. We need to update two comments, though.

2021-04-13 14:50 UTC, drwells commented on cmake/macros/macro_deal_ii_find_path.cmake
> +  # FIND_FILE gets its hands on it.
```suggestion
  # FIND_PATH gets its hands on it.
```

2021-04-13 14:50 UTC, drwells commented on cmake/macros/macro_deal_ii_find_program.cmake
> +  # FIND_FILE gets its hands on it.
```suggestion
  # FIND_PROGRAM gets its hands on it.
```

2021-04-15 23:38 UTC, bangerth commented
So done, thanks for the review @drwells !

2021-04-16 04:10 UTC, masterleinad approved these changes

2021-04-16 13:51 UTC, drwells approved these changes

2021-04-16 13:51 UTC, merged