Add FEEvaluation::print()
dealii/dealii pull request #12128
Opened 2021-05-03 19:19 UTC by peterrum

... references #10947.

2021-05-03 20:19 UTC, tjhei commented on include/deal.II/matrix_free/fe_evaluation.h
> +  out << " maximal precompiled degree: "
I would use "Maximum" instead.

2021-05-03 21:46 UTC, bangerth requested changes

2021-05-03 21:46 UTC, bangerth commented on include/deal.II/matrix_free/evaluation_template_factory.h
> +    max_precompiled_degree();
You could even make this function `constexpr`, and then it could be used to allocate arrays, for example.

2021-05-03 21:46 UTC, bangerth commented on include/deal.II/matrix_free/evaluation_template_factory.h
> +    max_precompiled_degree();
same here

2021-05-03 21:46 UTC, bangerth commented on include/deal.II/matrix_free/fe_evaluation.h
> +  print(StreamType &out) const;
Maybe call the function `print_summary()` if that is what it does? I would expect a function called `print()` to output the entire *state* of the object.

2021-05-03 21:46 UTC, bangerth commented on include/deal.II/matrix_free/fe_evaluation.h
> +  print(StreamType &out) const;
Separately, I would like it much better if the function simply took `std::ostream` as argument.

2021-05-03 21:46 UTC, bangerth commented on include/deal.II/matrix_free/fe_evaluation.h
> +           max_precompiled_degree()
This implementation really just prints a single piece of information. That doesn't match the documentation of the function, which suggests that it prints some kind of "summary" of things.

2021-05-04 10:34 UTC, kronbichler commented
Right now we print very limited information. The general question is whether we want to print the information for the currently constructed object (polynomial degree and quadrature formula), making the output depend on the constructed data, or simply print a generic (static) information about what kind of degrees and quadrature formulas use the fast path. The other question goes along the one by @bangerth regarding what kind of information we might want to print in addition. As I don't see much information beyond the precompiled paths, I think we might also pick another more specific name, e.g., `print_precompiled_degrees`.

2021-05-04 13:52 UTC, bangerth commented
On 5/4/21 4:35 AM, Martin Kronbichler wrote:
> As I don't see much information beyond the precompiled paths, I think we might 
> also pick another more specific name, e.g., |print_precompiled_degrees|.

But if that's all, why move the printing into a member function to begin with? 
It's no more effort to just return that number and do the printing in user 
space...

2021-05-04 13:54 UTC, peterrum commented
> But if that's all, why move the printing into a member function to begin with? It's no more effort to just return that number and do the printing in user space...

I did what the issue stated^^

But, we agreed on removing the print function and a function similar to:

https://github.com/dealii/dealii/blob/2d0211e4504d2d350fd92166e00ec614a39b8253/include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h#L2582-L2592

2021-05-04 20:12 UTC, peterrum commented
Next try!

2021-05-05 19:35 UTC, kronbichler approved these changes
Nice!

2021-05-05 19:38 UTC, peterrum commented
/rebuild

2021-05-06 06:56 UTC, kronbichler commented
Let us go ahead with this, as we now do exactly what @bangerth suggested.

2021-05-06 06:56 UTC, merged