Add simplex/mixed mesh examples to simplex module page
dealii/dealii pull request #12160
Opened 2021-05-09 10:03 UTC by peterrum

2021-05-09 10:04 UTC, peterrum commented on examples/doxygen/CMakeLists.txt
> +ENDFOREACH()
This is not working, yet. For some reason, deal.II is not found. Any ideas?

2021-05-16 15:47 UTC, drwells requested changes
I think its fine to add these examples in this way - it keeps them marked as experimental and outside of the official tutorial list.

2021-05-16 15:47 UTC, drwells commented on doc/doxygen/headers/simplex.h
> + * @dontinclude step_3_mixed.cc
```suggestion
```

I'm not sure what your original intent here but it probably was not to include `step_3_simplex.cc` twice in this file. Should this be something else?

2021-05-16 16:42 UTC, drwells commented
I think I understand the CMake problem. You are running code during the initial CMake run that tries to find deal.II, which doesn't make sense: deal.II hasn't yet compiled. In contrast, the examples compiled via `make examples` are configured by first extracting their dependencies with text processing and then adding them via `DEAL_II_ADD_INSOURCE_TARGET` rather than using their individual `CMakeLists.txt`, which avoids this problem.

This is just for example compilation - the documentation is fine (and everything works if examples are disabled).

What do we gain by compiling the simplex examples in this way? Don't we end up compiling them anyway inside the CI run?

2021-05-17 18:46 UTC, drwells requested changes
I have some minor CMake questions, otherwise 👍

2021-05-17 18:46 UTC, drwells commented on examples/CMakeLists.txt
> +
```suggestion
```

2021-05-17 18:46 UTC, drwells commented on examples/CMakeLists.txt
> +
```suggestion
```

2021-05-17 18:46 UTC, drwells commented on examples/CMakeLists.txt
> +          ENDIF()
If the examples are not installed (I don't see any calls to `INSTALL()` so I believe they are not) then this should not be set. Does this do something else that I don't understand?

2021-05-17 19:02 UTC, peterrum commented
Done!

2021-05-17 19:21 UTC, drwells approved these changes

2021-05-17 22:12 UTC, merged