CellIDTranslator:: add assert to prevent overflow
dealii/dealii pull request #12513
Opened 2021-06-28 10:12 UTC by peterrum

(partly) references #12337; only the second commit is relevant:

The assert message is as follows:
```
The violated condition was: 
    max_cell_index <= std::numeric_limits<types::global_cell_index>::max()
Additional information: 
    You have exceeded the maximal number of possible indices this function
    can handle. The current setup (n_coarse_cells=1, n_global_levels=12)
    requires 9817068105 indices but the current deal.II configuration only
    supports 4294967295 indices. You may want to consider to build deal.II
    with 64bit integers (-D DEAL_II_WITH_64BIT_INDICES="ON") to increase
    the limit of indices.
```

depends on #12492

2021-06-28 20:36 UTC, peterrum commented
This should be ready now. The depending PR is merged.

2021-06-29 13:26 UTC, drwells requested changes
This is nice functionality - I like that it gives a single integer instead of an array. That makes it somewhat more useful in serialization than `CellId`.

2021-06-29 13:26 UTC, drwells commented on include/deal.II/grid/cell_id_translator.h
> +     * Convert a @p cell of type CellAccessor or DoFCellAccessor to an index.
Shouldn't these be iterators and not accessors?

2021-06-29 13:26 UTC, drwells commented on include/deal.II/grid/cell_id_translator.h
> +     * would be refined globally.
```suggestion
     * were globally refined `n_global_levels` times.
```

2021-06-29 13:26 UTC, drwells commented on include/deal.II/grid/cell_id_translator.h
> +     * an index.
I don't understand what makes this function different from the version of `translate` that does not take an index. Could you elaborate?

2021-06-29 13:26 UTC, drwells commented on include/deal.II/grid/cell_id_translator.h
> +     * Convert a @p cell of type CellAccessor or DoFCellAccessor to an index.
If they are iterators - I would rather this be
```cpp
template <typename Accessor>
types::global_cell_index
translate(const TriaRawIterator<Accessor> &cell)
```
or `translate(const TriaIterator<Accessor> &cell)` for a little more type safety.

2021-06-29 13:29 UTC, drwells commented
Actually - my review isn't all that useful since this was already merged in #12504. Lets ignore those comments for now. Could you rebase so I can see what changed in this PR?

2021-06-29 14:12 UTC, peterrum commented
> Actually - my review isn't all that useful since this was already merged in #12504. Lets ignore those comments for now. Could you rebase so I can see what changed in this PR?

Done. I guess I can do a follow-up PR to address the above comments.

2021-06-29 14:13 UTC, drwells commented
Thanks!

2021-06-29 14:14 UTC, drwells requested changes
Looks good. It's pedantic, but for 100% standards compliance could you include `cstdint` and switch this to use `std::unit64_t`?

2021-06-29 14:24 UTC, peterrum commented
> Looks good. It's pedantic, but for 100% standards compliance could you include cstdint and switch this to use std::uint64_t?

Done!

2021-06-29 14:27 UTC, drwells approved these changes

2021-06-29 14:27 UTC, drwells commented
/rebuild

2021-06-29 19:58 UTC, kronbichler approved these changes

2021-06-29 19:59 UTC, merged