Add comments to wedge and pyramid FEs regarding degree
dealii/dealii pull request #12648
Opened 2021-08-12 07:44 UTC by peterrum

2021-08-12 14:30 UTC, drwells requested changes

2021-08-12 14:30 UTC, drwells commented on include/deal.II/fe/fe_pyramid_p.h
> + * also the documentation of ScalarLagrangePolynomialWedge.
```suggestion
 * also the documentation of ScalarLagrangePolynomialPyramid.
```

2021-08-12 14:30 UTC, drwells commented on include/deal.II/fe/fe_pyramid_p.h
> + * also the documentation of ScalarLagrangePolynomialWedge.
```suggestion
 * also the documentation of ScalarLagrangePolynomialPyramid.
```

2021-08-13 05:32 UTC, peterrum commented
@drwells Done!

2021-08-13 11:57 UTC, drwells approved these changes

2021-08-13 11:57 UTC, merged