Improve assert message in DictionaryPayLoad
dealii/dealii pull request #12937
Opened 2021-11-12 08:15 UTC by peterrum

closes #12933

2021-11-12 16:19 UTC, drwells requested changes

2021-11-12 16:19 UTC, drwells commented on include/deal.II/base/mpi_compute_index_owner_internal.h
> +                Assert(interval.first < interval.second, ExcInternalError());
We should move this assertion outside of the loop - it can never trigger in it since this is also the loop bounds.

2021-11-12 16:19 UTC, drwells commented on include/deal.II/base/mpi_compute_index_owner_internal.h
> +                Assert(interval.first < interval.second, ExcInternalError());
Oh, nevermind - there are no brackets around the first assert so this is outside the loop!

2021-11-12 16:19 UTC, drwells approved these changes

2021-11-12 16:20 UTC, drwells commented
/rebuild

2021-11-13 04:37 UTC, bangerth commented
Thanks! The tester seems to have run out of memory. Can you rebase and try again?

2021-11-13 18:06 UTC, peterrum commented
/rebuild

2021-11-13 21:36 UTC, merged