Improve build system when using Kokkos
dealii/dealii pull request #12940
Opened 2021-11-12 21:59 UTC by Rombur

This PR does the following:
 - disable vectorization if Kokkos is using CUDA. CUDA and vectorization do not mix well and we already disable vectorization when using CUDA
 - fix a bug where only the first flag from Kokkos was used. The others where ignored. The side effect of the PR is that I know get hundreds of shadowing warnings. I have a fix I'll open the PR later.
 - when using Kokkos with CUDA and if `DEAL_II_WITH_KOKKOS_BACKEND` is enable, check that Kokkos was compiled with lambda support. I will use `DEAL_II_WITH_KOKKOS_BACKEND` to guard the new Kokkos code, otherwise any one using Trilinos would use the new code.

2021-11-12 23:00 UTC, masterleinad approved these changes
Looks reasonable to me.

2021-11-17 01:38 UTC, tamiko requested changes

2021-11-17 01:38 UTC, tamiko commented on cmake/modules/FindKOKKOS.cmake
> +      ADD_FLAGS(DEAL_II_CXX_FLAGS "${KOKKOS_COMPILE_FLAGS_STR}")
```suggestion
```

2021-11-17 01:38 UTC, tamiko commented on cmake/modules/FindKOKKOS.cmake
> +      STRING(REGEX REPLACE ";" " " KOKKOS_COMPILE_FLAGS_STR "${KOKKOS_COMPILE_FLAGS}")
```suggestion
      STRING(REGEX REPLACE ";" " " KOKKOS_CXX_FLAGS "${KOKKOS_COMPILE_FLAGS}")
```

2021-11-17 01:39 UTC, tamiko commented on cmake/modules/FindKOKKOS.cmake
> +      STRING(REGEX REPLACE ";" " " KOKKOS_COMPILE_FLAGS_STR "${KOKKOS_COMPILE_FLAGS}")
You just need to set the `KOKKOS_CXX_FLAGS` variable and the build system should pick up the flags automatically (and properly report where they are coming from in `detailed.log`). :slightly_smiling_face:

2021-11-18 19:42 UTC, closed without merging