Allow accessing face numbers in data postprocessors
dealii/dealii pull request #13027
Opened 2021-12-03 23:32 UTC by bangerth

Classes derived from `DataPostprocessor` already have access to the cell being worked on right now, but when the work is done by `DataOutFaces`, they cannot access the face number. This patch fixes that, adds a test, and shows an example in the documentation.

/rebuild

2021-12-05 01:13 UTC, drwells requested changes
Nice feature.

Could you also change `set_cell()` to reset the face number to `numbers::invalid_unsigned_int`? The extra check would be nice.

2021-12-05 01:13 UTC, drwells commented on source/numerics/data_postprocessor.cc
> +// -------------------------
Could you fix this whitespace change?

2021-12-05 21:45 UTC, bangerth commented
Done as requested!

2021-12-06 13:33 UTC, drwells approved these changes

2021-12-06 13:33 UTC, merged