Explain the use of iterative solvers in the introduction of step-3.
dealii/dealii pull request #13270
Opened 2022-01-19 23:37 UTC by bangerth

The introduction of step-3 is in need of some expansion. One of the missing pieces is that it never says anything about how we solve linear systems.

Found while thinking about #9596.

2022-01-20 00:29 UTC, drwells requested changes
Looks good. I have some suggestions regarding consistenty of names and formatting.

2022-01-20 00:29 UTC, drwells commented on examples/step-3/doc/intro.dox
> +  weighted sum over a set of "quadrature points" on each cell. That is, we first split the
```suggestion
  weighted sum over a set of *quadrature points* on each cell. That is, we first split the
```
The other technical terms (like assembly) are emphasized so lets do that too.

2022-01-20 00:29 UTC, drwells commented on examples/step-3/doc/intro.dox
> +Conjugate Gradients for the solution of the linear systems, and we will
```suggestion
CG for the solution of the linear systems, and we will
```
we called it 'Conjugate Gradient' earlier (singular).

2022-01-20 00:29 UTC, drwells commented on examples/step-3/doc/intro.dox
> +a statement about the error we are willing to accept in our approximation
```suggestion
a statement about the error we are willing to accept in our approximate
```
again, just a consistency change

2022-01-20 00:29 UTC, drwells commented on examples/step-3/doc/intro.dox
> +<h3> "Assembling" the matrix and right hand side vector </h3>
```suggestion
<h3> *Assembling* the matrix and right hand side vector </h3>
```

2022-01-20 02:43 UTC, drwells approved these changes

2022-01-20 02:58 UTC, tjhei approved these changes
Very nice!👍

2022-01-20 20:08 UTC, kronbichler reviewed
A few comments regarding computing time and CG (not all comments are requests for change, some are merely comments).

2022-01-20 20:08 UTC, kronbichler commented on examples/step-3/doc/intro.dox
> +it finds the exact solution if the matrix is symmetric and positive definite.
```suggestion
in the absence of roundoff errors it finds the exact solution if the matrix is symmetric and positive definite.
```

2022-01-20 20:08 UTC, kronbichler commented on examples/step-3/doc/intro.dox
> +it had few advantages and was largely forgotten for a few decades. But,
If I recall the historic texts correctly, one of the main reasons was indeed the much higher sensitivity to roundoff errors than Gaussian elimination (today I would also mention data locality, but that was not an issue initially) - already for moderately ill-conditioned matrices (like `diag([1,2,3,...,100])` you can really see this happen.

2022-01-20 20:08 UTC, kronbichler commented on examples/step-3/doc/intro.dox
> +CG was rediscovered as a way to people realized that it is well suited for
I don't quite get this. Do you mean something like
```suggestion
CG was rediscovered as people realized that it is well suited for
```

2022-01-20 20:08 UTC, kronbichler commented on examples/step-3/doc/intro.dox
> +with at most ${\cal O}(N^2)$ operations, and in some cases substantially
```suggestion
with at most ${\cal O}(N^2)$ operations, and in many cases substantially
```
Poisson-type problems (which is one of the few cases where plain CG actually works) have a cost of O(N^{3/2}) in 2D and O(N^{4/3}) in 3D. The reason for the different powers is that in 3D, for the same N ~ h^{-3}, the ratio between the domain size and cell length is lower.

2022-01-20 21:48 UTC, bangerth commented on examples/step-3/doc/intro.dox
> +feasible and it would take modern processors on the order of 1-10 seconds
Ah, interesting. In my head, I thought that 861M operations will each take ~3 cycles, which gives us about a second. Then I padded the number by a safety factor for bandwith limitations. But thinking about it, a 1089x1089 matrix comfortably fits into the cache these days, and I think what you're saying is that with XMM, SSE, AVX, ... you get enough parallelism that things are actually that much faster. Fun.

2022-01-20 21:54 UTC, bangerth commented on examples/step-3/doc/intro.dox
> +it had few advantages and was largely forgotten for a few decades. But,
Yes, round-off is a concern, but that's something that I believe people knew how to deal with -- with iterative refinement. Of course, round-off was a concern also for direct solver, given that they only had single-precision at the time. Basically, the whole issue of forward and backward stability analysis is a product of having only single precision available.

One could expand on all of this, but in the end, that isn't the place for it. I just wanted to briefly touch on the basic motivation to not use direct solvers in FEM codes, and so saving the historical context for another place might be the place to go :-) I don't think you suggested anything else either.

2022-01-20 22:07 UTC, bangerth commented
So modified.

2022-01-20 22:11 UTC, bangerth commented on examples/step-3/doc/intro.dox
> +with at most ${\cal O}(N^2)$ operations, and in some cases substantially
I assume you were talking about direct solvers:
Just for completeness, I think it's O(N^{5/3}) in 3d -- worse than the 3/2 in 2d. In 2d, you can re-sort DoFs in such a way that the bandwidth of the matrix is b=O(sqrt(N)), but in 3d the bandwidth becomes b=O(N^{2/3}).

2022-01-21 07:42 UTC, kronbichler commented on examples/step-3/doc/intro.dox
> +it had few advantages and was largely forgotten for a few decades. But,
Exactly, I didn't want to suggest anything else here, I just wanted to add some thoughts.

2022-01-21 07:43 UTC, kronbichler approved these changes

2022-01-21 07:45 UTC, merged