Introduce ReferenceCell::n_isotropic_children().
dealii/dealii pull request #13287
Opened 2022-01-24 18:23 UTC by bangerth

I had a need to query the number of children of a cell, but it turns out that there is currently no function in `ReferenceCell` to do that. So I added one, but this is WIP because I don't know what we do (or intend to do) for refinement of tetrahedra and pyramids. Anyone remember the correct numbers to be added there?

/rebuild

2022-01-24 18:36 UTC, drwells commented
We are using 8 children per tet: see https://github.com/dealii/dealii/blob/master/source/grid/tria.cc#L5127. This PR would be a nice place to un-hardcode some of those numbers.

I don't think we have figured out how to refine pyramids yet so making that fail is the right choice.

2022-01-24 19:02 UTC, bangerth commented
Maybe use it like in that last commit?

2022-01-24 19:08 UTC, bangerth commented
I pushed one more commit that cleans up a piece of code that wasn't immediately clear to me. I *think* that what it wants to test is that a number if zero/not-zero. I added an assertion that provides us with another nice use of the new function.

2022-01-24 19:15 UTC, drwells approved these changes

2022-01-24 23:56 UTC, bangerth commented
The last commit failed; the new version of it should now succeed. It illustrates why we decided to deprecate `number_of_children()` and should be using `n_children()` instead :-)

2022-01-26 14:07 UTC, drwells commented on include/deal.II/grid/reference_cell.h
> +    return 9;
Isn't this 8 in line 5127 of tria.cc?

2022-01-26 17:24 UTC, drwells requested changes
I am pretty sure that should be an 8 - lets hold off on merging.

2022-01-26 17:40 UTC, peterrum commented on include/deal.II/grid/reference_cell.h
> +    return 9;
Indeed.

2022-01-26 18:34 UTC, bangerth commented
I fatfingered the number that @drwells provided for tetrahedra in a comment above. Sorry about that. It's fixed here now.

2022-01-26 20:53 UTC, drwells approved these changes

2022-01-26 21:41 UTC, merged