Add ArborXWrappers::DistributedTree
dealii/dealii pull request #13394
Opened 2022-02-16 02:32 UTC by Rombur

This PR adds supports for `ArborX::DistributedTree`. This is the distributed version of the `ArborX::BVH` which we already have wrappers for.  With this library, we can do spatial search and nearest neighbors search when the points/bounding boxes are distributed.

2022-02-17 16:57 UTC, masterleinad requested changes

2022-02-17 16:57 UTC, masterleinad commented on include/deal.II/arborx/distributed_tree.h
> +     */
I think we should mention restrictions on the type/interface of `queries` here.

2022-02-18 03:09 UTC, Rombur commented
I have updated the comments

2022-02-18 15:42 UTC, Rombur commented on include/deal.II/arborx/distributed_tree.h
> +     * Constructor. Use a vector of BoundingBox @p bounding_boxes as primitives.
I'll add a comment but to answer your question, these are local bounding boxes. The way ArborX works in the distributed case is by building two trees. First it builds a "regular" tree that is only local. Then the root of the local trees are used to create a second tree that it is used to know on which processors there might be something interesting.

With the current wrappers, we return the indices and the ranks of the bounding boxes that satisfy the predicate but ArborX has a callback system that can be used to execute a function on a remote processor and get the results back. I still need to think of a nice way to expose that capability.

2022-02-18 16:34 UTC, Rombur commented
@masterleinad good catch. It should be good now.

2022-02-25 13:03 UTC, Rombur commented
@masterleinad ping

2022-02-25 15:04 UTC, masterleinad approved these changes

2022-02-25 16:05 UTC, Rombur commented
/rebuild

2022-02-27 09:51 UTC, luca-heltai approved these changes

2022-02-28 22:12 UTC, Rombur commented
> Can you also add the DEAL_II_ARBORX_WITH_MPI to the doxygen file, so that the documentation shows up online?

Done

2022-03-01 07:50 UTC, merged