Change one GitHub Workflow CI check to use C++20
dealii/dealii pull request #13535
Opened 2022-03-12 17:27 UTC by masterleinad

In response to https://github.com/dealii/dealii/pull/13508#issuecomment-1064742478.

2022-03-12 17:28 UTC, peterrum approved these changes
Thanks!

2022-03-17 18:10 UTC, drwells requested changes

2022-03-17 18:22 UTC, masterleinad commented on .github/workflows/linux.yml
> +      uses: egor-tensin/build-boost@v1
I ran into a compilation problem with C++20 that was resolved in later versions.

2022-03-17 18:23 UTC, drwells approved these changes

2022-03-17 18:23 UTC, drwells commented
/rebuild

2022-03-17 21:21 UTC, merged

2022-05-04 06:37 UTC, luca-heltai commented on .github/workflows/linux.yml
> +      uses: egor-tensin/build-boost@v1
@masterleinad, out of curiosity, was the compilation problem related to the python bindings, or something more essential?

2022-05-04 12:34 UTC, masterleinad commented on .github/workflows/linux.yml
> +      uses: egor-tensin/build-boost@v1
It was something more essential. There was some kind of incompatibility of older boost versions with newer gcc versions and C++20 IIRC. I don't remember the specific boost library but I'm pretty sure it wasn't python.