Add Kokkos backend
dealii/dealii pull request #13549
Opened 2022-03-17 19:05 UTC by masterleinad

Builds on top of https://github.com/dealii/dealii/pull/13149 and tries to initialize `Kokkos` when needed and finalize it by registering `Kokkos::finalize` to `std::atexit`. In my tests that worked fine with `Kokkos+Cuda` and initial tests with `Kokkos+Serial` also looked 
good.
It needs more thorough tests, though.

2022-03-17 19:28 UTC, tamiko requested changes

2022-03-17 19:28 UTC, tamiko commented on cmake/setup_cached_variables.cmake
> +LIST(APPEND DEAL_II_FEATURES KOKKOS_BACKEND)
I know that this is not semantically elegant, but would you mind renaming the variable to `DEAL_II_WITH_KOKKOS_BACKEND`?

The reason being that this entire feature mechanism (i.e., when you add stuff to `DEAL_II_FEATURES` only works with the prefix `DEAL_II_WITH`). For example, a clean configure of your pull request currently shows:
```
#        DEAL_II_WITH_KOKKOS set up with external dependencies
#      ( DEAL_II_WITH_KOKKOS_BACKEND =  )
```

2022-03-17 19:28 UTC, tamiko commented on include/deal.II/base/config.h.in
> +#cmakedefine DEAL_II_USE_KOKKOS_BACKEND
Then this would be not necessary any more :-)

2022-03-23 00:14 UTC, bangerth commented
I would prefer if the `ensure_kokkos_initialized()` function would simply call `Assert()`. I continue to think that we should initialize Kokkos in `MPI_InitFinalize()` or, alternatively, in a `Kokkos_InitFinalize()` class that one can use in non-MPI programs. If you then have your `ensure_kokkos_initialized()` function simply terminate, this is an indication that a program just needs to add the initialization by hand.

2022-03-23 12:42 UTC, masterleinad commented
@bangerth At the moment, I am focussing on getting this pull request working with `Kokkos+CUDA` and `DEAL_II_WITH_CUDA=ON`. Then, I'm curious to see if calling `std::atexit` actually works with that configuration. If it does, I would consider it a long(er) term solution that could be done in a follow-up pull request, though. For now, it's at least helpful to automatically initialize `Kokkos` to be able to run the unit tests without modifying tests.

Of course, I'm open to other suggestions.

2022-12-05 13:43 UTC, masterleinad commented
Superseded by #14510.

2022-12-05 13:43 UTC, closed without merging