Create coarse mesh out of a CGAL::Surface_mesh
dealii/dealii pull request #13705
Opened 2022-05-09 23:28 UTC by fdrmrc

Given a closed CGAL::Surface_mesh, this function fills its interior with (few) tets and store the resulting 3D tria in the second argument of the present utility function. Starting from that coarse 3D object, one can create a `Quadrature` to integrate over it by exploiting `QGaussSimplex`. 

Therefore in the follow-up PR I'd add the utlity `Quadrature<...>
 compute_global_quadrature_rule(const CGALTtriangulation& tr);`

and these together allow to compute quadrature rules over the result of (meaningful) boolean operations between deal.II 3D cells.

2022-05-10 09:02 UTC, peterrum commented on include/deal.II/cgal/utilities.h
> +    using namespace CGAL::parameters;
Please don't use  `using namespace`.

2022-05-10 09:51 UTC, fdrmrc commented on include/deal.II/cgal/utilities.h
> +   * rules over each tetrahedron.
I should've been more precise, I'm sorry.
The surface_mesh is indeed what you wrote. With "coarse mesh" I mean a coarse tetrahedralization of the volumetric region bounded by that closed surface.
Once you have this, for instance, you can get vertices of each tetrahedron and compute Quadratures

2022-05-10 09:51 UTC, fdrmrc commented on include/deal.II/cgal/utilities.h
> +   * @param [in] sm The (closed) surface mesh to be filled.
You're right. I'll remove the part you highlighted.

2022-05-10 09:51 UTC, fdrmrc commented on cmake/config/template-arguments.in
> -                CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt;
We don't need that, so I removed it

2022-05-10 14:46 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +                                        "input_grids/tetrahedron.off"};
you should also add these two files to the input_grids directory.

2022-05-10 14:47 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +#  endif
Move this inside the CGALWrappers namespace. Same problemw with the space that you had in the test file.

2022-05-10 14:49 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +#  endif
Also, I'd rename it following deal.II conventions: 

```
using ConcurrencyTag = CGAL::Parallel_tag;
...
```

2022-05-10 14:49 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +#ifdef CGAL_CONCURRENT_MESH_3
This should become CGALWrappers::ConcurrencyTag

2022-05-10 17:15 UTC, fdrmrc commented
Thanks Peter and Luca! I've addressed your comments.

2022-05-11 15:15 UTC, luca-heltai requested changes
Just a few more changes for me, and then this is ready from my side. I'll wait for @peterrum to approve it though, since I followed your implementation along the way.

2022-05-11 15:15 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +  using Concurrency_tag = CGAL::Sequential_tag;
```suggestion
  using ConcurrencyTag = CGAL::Sequential_tag;
```

2022-05-11 15:15 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +      Mesh_triangulation_3<Mesh_domain, CGAL::Default, Concurrency_tag>::type;
```suggestion
      Mesh_triangulation_3<Mesh_domain, CGAL::Default, ConcurrencyTag>::type;
```

2022-05-11 15:15 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
```suggestion
using K = CGAL::Exact_predicates_inexact_constructions_kernel;
```

2022-05-11 15:15 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +      tria.output_to_medit(off_file_medit, false);
```suggestion
      {
        std::ofstream off_file_medit("coarse.mesh");
        ++counter;
        tria.output_to_medit(off_file_medit, false);
      }
      cat_file("coarse.mesh");
```

2022-05-11 15:15 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +        }
```suggestion
```

2022-05-11 15:15 UTC, luca-heltai commented on tests/cgal/cgal_surface_mesh_02.cc
> +      deallog << '\n' << std::endl;
```suggestion
      deallog << std::endl << std::endl;
```

2022-05-11 15:15 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +   *
```suggestion
   * Given a closed CGAL::Surface_mesh, this function fills the
   * region bounded by the surface with tets, keeping them as coarse as possible.
   * 
   * The number of the generated tetrahedrons depends on the refinement level of surface mesh. This function
   * does not attempt to construct a fine triangulation, nor to smooth the final result. If you need finer control on 
   * the resulting triangulation, you should consider using directly CGAL::make_mesh_3().
   *
```

2022-05-11 15:15 UTC, luca-heltai commented on include/deal.II/cgal/utilities.h
> +  using Concurrency_tag = CGAL::Parallel_tag;
Let's keep our notation in our wrappers.

2022-05-11 15:18 UTC, peterrum commented
> Just a few more changes for me, and then this is ready from my side. I'll wait for @peterrum to approve it though, since I followed your implementation along the way.

I'll take a look at the most tomorrow. Not sure I get around to it today...

2022-05-12 11:50 UTC, peterrum commented
/rebuild

2022-05-12 15:14 UTC, fdrmrc commented
> But let me ask you a question: the new function just converts one CGAL class to another one. Is it supposed to be used in combination with one of the other new functions or how should it be used together with deal.II?

It's supposed to be an utility used in combination with the new functions. In practice, once you have this coarse tetrahedralization, you can call
```
template<typename CGALTria>
Quadrature<Tr::Point::Ambient_dimension::value>  compute_quadrature(const CGALTria &tria, const unsigned int degree)
```
which gives a Quadrature rule over the polyhedra. That's still something CGAL-related, to be called inside the following:

```
  template <int dim0, int dim1, int spacedim,>
  dealii::Quadrature<spacedim>
  compute_quadrature_on_boolean_operation(
    const typename dealii::Triangulation<dim0, spacedim>::cell_iterator &cell0,
    const typename dealii::Triangulation<dim1, spacedim>::cell_iterator &cell1,
    const unsigned int                                                   degree,
    const Mapping<dim0, spacedim> &mapping0 =
      (dealii::ReferenceCells::get_hypercube<dim0>()
         .template get_default_linear_mapping<dim0, spacedim>()),
    const Mapping<dim1, spacedim> &mapping1 =
      (dealii::ReferenceCells::get_hypercube<dim1>()
         .template get_default_linear_mapping<dim1, spacedim>()));
```


(I'm going to open a PR for these last two)

2022-05-12 15:23 UTC, luca-heltai commented
Also, this together with the boolean operation and another PR that is currently underway, will permit to do the following:

~~~c++
Triangulation<3,3> tria1;
Triangulation<3,3> tria2;
... // Fill tria1, tria2
Triangulation<3,3> tria3;
compute_booloean_operation(tria1,tria2,tria3, bool_op);
~~~
I.e., compute boolean operations on grids, like subtracting balls from cubes, and obtaining a new triangulation in return.

2022-05-13 13:07 UTC, peterrum approved these changes

2022-05-14 09:50 UTC, luca-heltai approved these changes
I'm fine with the current status. Let's go ahead and merge. Another PR is waiting for this.

2022-05-14 09:50 UTC, merged