Convert Triangulation<2,3> to Triangulation<3>
dealii/dealii pull request #13767
Opened 2022-05-20 22:32 UTC by fdrmrc

This converts a closed deal.II Triangulation<2,3> to a Triangulation<3>, filling the latter with tetrahedrons. Named parameters can be used to control the size and the quality of the final mesh. 
I put this into `GridTools`, but  I'm happy to move this back if you think GridTools is not the right place.

2022-05-22 15:53 UTC, luca-heltai commented
I think this should go in `grid_geneerator.h`, next to its "inverse", i.e., the function that extracts a boundary mesh from a Triangulation.

2022-05-22 15:57 UTC, luca-heltai requested changes
Besides moving it to `grid_generator.h`, I think the documentation should be filled with the information about the additional parameters.

2022-05-22 15:57 UTC, luca-heltai commented on include/deal.II/grid/grid_tools.h
> +   * the final triangulation.
Can you copy here the blob about the parameters of mesh_criteria_3 that we have in the other function?

2022-05-22 15:57 UTC, luca-heltai commented on tests/cgal/cgal_triangulation_07.cc
> +  // cat_file("tria_surface_to_volumetric.vtk");
```suggestion
  remove("tria_surface_to_volumetric.vtk");
```

2022-05-22 21:10 UTC, peterrum reviewed
Very nice!

2022-05-22 21:10 UTC, peterrum commented on include/deal.II/grid/grid_tools.h
> +                                  Args... cgal_args);
Personally, I would prefer to introduce an `AdditionalData`.

2022-05-22 21:10 UTC, peterrum commented on include/deal.II/grid/grid_tools.h
> +#endif
Why is this here? Isn't this the same as above?

2022-05-22 21:10 UTC, peterrum commented on include/deal.II/grid/grid_tools.h
> +                                  Args... cgal_args);
Can we move `#ifdef DEAL_II_WITH_CGAL` within the function and assert it there?

2022-05-22 21:12 UTC, fdrmrc commented
@peterrum I pushed right after you wrote the review!

2022-05-22 21:12 UTC, peterrum commented
One question: the original surface mesh determines the cells of the volume mesh on the surface or are the cells unrelated?

2022-05-22 21:29 UTC, fdrmrc commented
> One question: the original surface mesh determines the cells of the volume mesh on the surface or are the cells unrelated?

They're currently unrelated. The use case I had in mind is like the one in the test: one just starts with a deal.II tria describing the surface and fills it. It should not be a problem however to record the topological information about the first deal.II surface tria and use it to create the volumetric one.

2022-06-03 23:49 UTC, fdrmrc commented on include/deal.II/grid/grid_generator.h
> +                                  Args... cgal_args);
Sure. As soon as the other patch is okay, I can update this!

2022-06-06 14:59 UTC, fdrmrc commented
So done, this should be good to go now.  
Since the function is not templated anymore, I've moved it inside `grid_generator.cc`. 

Also, I took the liberty to move the two utility functions that convert points back and forth from deal.II to CGAL in a separate header, fixing some issues with headers inclusions I hadn't noticed before.

2022-06-06 17:14 UTC, luca-heltai approved these changes
Minor change required: add an implementation stub that throws ExcNotImplemented if cgal is not found.

2022-06-06 17:14 UTC, luca-heltai commented on source/grid/grid_generator.cc
> +#  endif
Can you add a default implementation that throws an error saying that the function needs CGAL to be installed?

2022-06-07 07:46 UTC, kronbichler approved these changes
Looks good, apart from some adaptations to the comments.

2022-06-07 07:46 UTC, kronbichler commented on include/deal.II/grid/grid_generator.h
> +   * by filling it with tetrahedrons.
```suggestion
   * by filling it with tetrahedra.
```

2022-06-07 07:46 UTC, kronbichler commented on include/deal.II/grid/grid_generator.h
> +   * https://doc.cgal.org/latest/Mesh_3/index.html) for more information.
Can you please adapt this and the text below, as we have now introduced AdditionalData.

2022-06-07 17:47 UTC, fdrmrc commented
I'm addressing Luca's comment, please don't merge

2022-06-08 09:43 UTC, fdrmrc commented
I rebased this PR onto the smaller ones #13928  and #13929, so that here there's effectively only the implementation of `surface_tria_to_volumetric()`.

2022-06-10 17:14 UTC, fdrmrc commented
Rebased on top of master.

2022-06-10 18:42 UTC, kronbichler approved these changes

2022-06-11 10:21 UTC, fdrmrc commented
The implementation of the present function has been moved in `grid_generator_cgal.cc`, following #13954

2022-06-11 13:39 UTC, kronbichler approved these changes

2022-06-11 13:39 UTC, merged