Fix two tests with complex PETSc
dealii/dealii pull request #13960
Opened 2022-06-12 19:05 UTC by kronbichler

Note that I do not have a complex PETSc version around locally, so this should be taken with a grain of salt.

2022-06-12 19:05 UTC, kronbichler commented
Test failures see https://cdash.dealii.43-1.org/test/14719224 and https://cdash.dealii.43-1.org/test/14721238

2022-06-13 04:20 UTC, tamiko approved these changes

2022-06-13 04:22 UTC, tamiko commented
@kronbichler I will check this real quick on the tester.

2022-06-13 05:09 UTC, tamiko requested changes

2022-06-13 05:09 UTC, tamiko commented on tests/petsc_complex/assemble_01.cc
> +  DynamicSparsityPattern dsp(n, n);
```
diff --git a/tests/petsc_complex/assemble_01.cc b/tests/petsc_complex/assemble_01.cc
index b055c8a93b..e31b5a3c49 100644
--- a/tests/petsc_complex/assemble_01.cc
+++ b/tests/petsc_complex/assemble_01.cc
@@ -19,6 +19,7 @@
 // combinations of PETScWrappers objects is correctly instantiated and works.
 
 #include <deal.II/lac/affine_constraints.h>
+#include <deal.II/lac/dynamic_sparsity_pattern.h>
 #include <deal.II/lac/full_matrix.h>
 #include <deal.II/lac/petsc_sparse_matrix.h>
 #include <deal.II/lac/petsc_vector.h>
```

2022-06-13 05:13 UTC, kronbichler commented on tests/petsc_complex/assemble_01.cc
> +  DynamicSparsityPattern dsp(n, n);
Thank you!

2022-06-13 09:46 UTC, merged