Show a formula.
dealii/dealii pull request #14146
Opened 2022-07-18 21:19 UTC by bangerth

Like a picture, it's easier to see what this is this way.

/rebuild

2022-07-19 09:00 UTC, Rombur approved these changes

2022-07-19 09:51 UTC, marcfehling requested changes

2022-07-20 02:10 UTC, bangerth commented
Oh, doh. So fixed!

2022-07-20 06:04 UTC, marcfehling approved these changes

2022-07-20 06:05 UTC, merged