Test Kokkos on GPU
dealii/dealii pull request #14461
Opened 2022-11-23 20:09 UTC by zjiaqi2018

Test using Kokkos on GPU, but only works when `CMAKE_BUILD_TYPE=Debug ` is set. @tjhei

2022-11-23 20:19 UTC, zjiaqi2018 commented
The script to build deal.ii
```
cmake  -D CMAKE_INSTALL_PREFIX=../installed-kokkos \
              -D CMAKE_BUILD_TYPE=Debug \
              -D CMAKE_CXX_COMPILER=/home/jiaqi2/kokkos/bin/nvcc_wrapper \
              -D DEAL_II_CUDA_FLAGS='-arch=sm_70' \
              -D DEAL_II_CXX_FLAGS='-Werror -Wno-non-template-friend' \
              -D DEAL_II_EARLY_DEPRECATIONS=ON \
              -D DEAL_II_WITH_CUDA="ON" \
              -D DEAL_II_WITH_KOKKOS="ON" \
              -D KOKKOS_DIR=/home/jiaqi2/kokkos/installed \
              -D DEAL_II_WITH_MPI="ON" \
              -D DEAL_II_WITH_P4EST="ON" \
              -D DEAL_II_WITH_TRILINOS="OFF" \
              -D DEAL_II_COMPONENT_EXAMPLES="OFF" \
	      ../dealii
```

2022-11-23 20:50 UTC, masterleinad requested changes
```
 DEAL_II_CUDA_FLAGS='-arch=sm_70'
```
doesn't have any effect anymore. We only use flags coming from `Kokkos`.

Also, note that we already have a quick test which also tests basic functionality (and isn't limited to `CUDA`), see https://github.com/dealii/dealii/blob/master/tests/quick_tests/kokkos.cc. In general, I think we should go away from tests that only work with `CUDA` as opposed to using the default execution space in `Kokkos`.

Also, why would this only work in `Debug` mode?

2022-11-23 20:50 UTC, masterleinad commented on tests/cuda/test_kokkos.cc
> +      }
```suggestion
    // Initialize y vector on host.
    Kokkos::deep_copy(h_y, 1);
    
    // Initialize x vector on host.
    Kokkos::deep_copy(h_x, 1);
```

2022-11-23 20:50 UTC, masterleinad commented on tests/cuda/test_kokkos.cc
> +    using ViewVectorType = Kokkos::View<double *, Kokkos::LayoutLeft, MemSpace>;
```suggestion
    using ExecSpace = MemSpace::execution_space;
    using range_policy = Kokkos::RangePolicy<ExecSpace>;

    using ViewVectorType = Kokkos::View<double *>;
```

2022-11-23 20:50 UTC, masterleinad commented on tests/cuda/test_kokkos.cc
> +// Compute the inner product of two vectors on the GPU using Kokkos.
```suggestion
// Compute the inner product of two vectors on the default execution space using Kokkos.
```

2022-11-23 20:58 UTC, masterleinad commented
Also, this doesn't use deal.II at all.

2022-11-24 17:36 UTC, zjiaqi2018 commented
> ```
>  DEAL_II_CUDA_FLAGS='-arch=sm_70'
> ```
> 
> doesn't have any effect anymore. We only use flags coming from `Kokkos`.

Should we remove it from workflows/linux.yml?
> 
> Also, note that we already have a quick test which also tests basic functionality (and isn't limited to `CUDA`), see https://github.com/dealii/dealii/blob/master/tests/quick_tests/kokkos.cc. In general, I think we should go away from tests that only work with `CUDA` as opposed to using the default execution space in `Kokkos`.
> 
Then this test is not necessary anymore. 

> Also, why would this only work in `Debug` mode?
It works in both release and debug modes after I rebase to master.

2022-11-24 17:36 UTC, closed without merging