PETScWrappers:BlockSparseMatrix: create PETSc MATNEST
dealii/dealii pull request #14592
Opened 2022-12-20 10:30 UTC by luca-heltai

This is the first step towards using PETSc solvers with our BlockMatrix wrappers.

2022-12-20 14:08 UTC, drwells requested changes

2022-12-20 14:08 UTC, drwells commented on doc/news/changes/minor/20221220StefanoZampini-b
> +(StefanZampini, 2022/12/20)
```suggestion
(Stefano Zampini, 2022/12/20)
```
:)

2022-12-20 14:08 UTC, drwells commented on include/deal.II/lac/petsc_block_sparse_matrix.h
> +      operator Mat() const;
```suggestion
      operator const Mat &() const;
```
Lets make this consistent with the vector class.

2022-12-20 14:08 UTC, drwells commented on source/lac/petsc_parallel_block_sparse_matrix.cc
> +      AssertThrow(ierr == 0, ExcPETScError(ierr));
```suggestion
      AssertNothrow(ierr == 0, ExcPETScError(ierr));
```
No throwing from dtors

FYI: like the other PR: we do have `destroy_matrix()` but it doesn't do anything but call `MatDestroy()` these days. It was written at a time when we supported old versions of PETSc which had a different API. I'd prefer to just remove the function and call `MatDestroy()` directly.

2022-12-20 14:08 UTC, drwells commented on source/lac/petsc_parallel_block_sparse_matrix.cc
> +      AssertThrow(ierr == 0, ExcPETScError(ierr));
✔️

2022-12-20 14:10 UTC, drwells commented
This looks good. I wrote a much worse version of this in September to make step-32 work with PETSc.

2022-12-20 16:48 UTC, drwells approved these changes

2022-12-20 17:59 UTC, stefanozampini approved these changes

2022-12-20 18:22 UTC, luca-heltai commented
/rebuild

2022-12-21 06:20 UTC, luca-heltai commented
CI fails when installing mold linker.

2022-12-21 15:52 UTC, luca-heltai commented
@drwells, shall we merge?

2022-12-21 16:09 UTC, merged