Use initlog() in more tests.
dealii/dealii pull request #14719
Opened 2023-01-24 15:35 UTC by drwells

Part of #7196. I was reminded of this when reviewing one of the PETSc patches - its pretty easy to automatically convert many of these with a python script.

2023-01-24 17:48 UTC, tamiko requested changes
It looks like the conversion did not completely work for a small number of tests.

2023-01-24 17:48 UTC, tamiko commented on tests/bits/step-10-high-order.cc
>    deallog << std::setprecision(16);
double `deallog <<`

2023-01-24 17:48 UTC, tamiko commented on tests/bits/step-10-high-order.cc
> -  logfile << std::setprecision(16);
and you don't set the precision of the logfile any more (as you do for some other tests).

2023-01-24 18:37 UTC, drwells commented
The tests passed locally for me but it's worth cleaning things up - both comments should now be fixed in all files.

2023-01-24 20:24 UTC, masterleinad approved these changes

2023-01-25 21:39 UTC, bangerth approved these changes

2023-01-25 21:39 UTC, bangerth commented
@tamiko is still blocking the merge. I'll let him comment/pull the trigger.

2023-01-25 23:58 UTC, tamiko approved these changes

2023-01-25 23:59 UTC, tamiko commented
@bangerth Feel free to simply dismiss such a change request from me as "resolved" in the future.

2023-01-25 23:59 UTC, merged