Fix FEInterfaceValues::reinit when no dominating FE has been found.
dealii/dealii pull request #15031
Opened 2023-04-05 22:25 UTC by marcfehling

Fixes #15021. Related to https://github.com/dealii/dealii/pull/14547#discussion_r1053319521.

I cleaned up the `make_2_cells` functions first as we have a function `hyper_line` that does exactly the same.

Next comes the actual fix to the problem of neighboring FEs that do not dominate each other. I used the test that @simonsticko provided, in which I noticed that `distribute_dofs()` was called at the wrong place. Luckily this throws an error, so I improved the error message.

@jppelteret @fdrmrc -- FYI

2023-04-05 22:28 UTC, marcfehling commented
@bangerth -- Officially, the [`find_dominated_fe`](https://www.dealii.org/developer/doxygen/deal.II/classhp_1_1FECollection.html#a719793132cab791f215ee96b4d5f0c75) function still returns an `unsigned int`. I simply didn't make it so far in #13595 yet. Let's leave it this way for now.

https://github.com/dealii/dealii/blob/0cf9555689bad78df6ec9086a7bba3d82413d182/include/deal.II/fe/fe_interface_values.h#L2494-L2496

2023-04-06 17:41 UTC, bangerth requested changes
I don't think this is right yet.

2023-04-06 17:42 UTC, bangerth commented
The first commit is of course correct in itself. Feel free to submit it separately.

2023-04-07 20:58 UTC, bangerth commented on include/deal.II/fe/fe_interface_values.h
> +      }();
As stated elsewhere, I don't think this is right. We should be choosing the same quadrature formula regardless of which side of a face you approach.

2023-04-17 18:04 UTC, closed without merging