Use -Werror again in enable_if_supported
dealii/dealii pull request #15549
Opened 2023-06-30 20:33 UTC by masterleinad

Reverts #15532. Let's see if there is any other reason for not using `-Werror`.

2023-06-30 20:33 UTC, masterleinad commented
/rebuild

2023-07-01 06:05 UTC, kronbichler approved these changes
This looks good to me, and at least the OSX platform seems to be happy. Let's wait for additional opinions.

2023-07-01 15:05 UTC, tamiko requested changes

2023-07-01 15:05 UTC, tamiko commented on cmake/macros/macro_enable_if_supported.cmake
> +  CHECK_CXX_COMPILER_FLAG("-Werror" DEAL_II_HAVE_FLAG_werror)
```suggestion
  CHECK_CXX_COMPILER_FLAG("-Werror" DEAL_II_HAVE_FLAG_Werror)
```

2023-07-01 15:05 UTC, tamiko commented on cmake/macros/macro_enable_if_supported.cmake
> +  if(DEAL_II_HAVE_FLAG_werror)
```suggestion
  if(DEAL_II_HAVE_FLAG_Werror)
```

2023-07-01 16:51 UTC, tamiko approved these changes

2023-07-01 22:14 UTC, merged