Add InitFinalize base class of MPI_InitFinalize
dealii/dealii pull request #15572
Opened 2023-07-01 21:33 UTC by Rombur

Alternative to https://github.com/dealii/dealii/pull/14884

It creates a new base class `InitFinalize` that allows a more fine grain control over which external libraries we initialize/finalize. I have added a new function `finalize` to allow user to finalize the libraries without having the object going out-of-scope.

2023-07-02 00:43 UTC, bangerth commented
```
In file included from /Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/mpi.h:22:
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:169:20: error: unknown type name 'MPI_Request'
  register_request(MPI_Request &request);
                   ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:175:22: error: unknown type name 'MPI_Request'
  unregister_request(MPI_Request &request);
                     ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:209:19: error: use of undeclared identifier 'MPI_Request'
  static std::set<MPI_Request *> requests;
                  ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:209:32: error: expected expression
  static std::set<MPI_Request *> requests;
                               ^
In file included from /Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/source/dofs/dof_handler.cc:20:
In file included from /Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/mpi.templates.h:22:
In file included from /Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/mpi.h:22:
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:169:20: error: unknown type name 'MPI_Request'
  register_request(MPI_Request &request);
                   ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:175:22: error: unknown type name 'MPI_Request'
  unregister_request(MPI_Request &request);
                     ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:209:19: error: use of undeclared identifier 'MPI_Request'
  static std::set<MPI_Request *> requests;
                  ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-15572/include/deal.II/base/init_finalize.h:209:32: error: expected expression
  static std::set<MPI_Request *> requests;
                               ^
4 errors generated.
```

2023-07-02 11:07 UTC, kronbichler commented
FYI @sloede

2023-07-03 23:40 UTC, tamiko commented
We have at least one failing test with:
```
--------------------------------------------------------
An error occurred in line <260> of file </__w/dealii/dealii/source/base/init_finalize.cc> in function
    dealii::InitFinalize::InitFinalize(int&, char**&, const dealii::InitializeLibrary&, unsigned int)
The violated condition was: 
    nth_process_on_host > 0
```

2023-07-04 01:56 UTC, tamiko approved these changes

2023-07-13 03:15 UTC, masterleinad commented
This needs to be rebased and probably needs a changelog entry.

2023-12-01 18:57 UTC, Rombur commented
I forgot I still had this PR opened. I've rebased it on master and fixed the conflicts.

2024-03-20 09:29 UTC, kronbichler approved these changes
I think it is time to move forward with this PR. I like this path, and would opt to merge it soon. Unless someone else speaks up, I will merge this tomorrow.

2024-03-20 11:56 UTC, masterleinad requested changes
Can we add a test that doesn't initialize all libraries?

2024-03-20 11:56 UTC, masterleinad commented on include/deal.II/base/init_finalize.h
> + * first one.
```suggestion
 * Global operator which returns an object in which all bits are set that are
 * set both in the first and second argument.
```

2024-03-20 16:29 UTC, Rombur commented on include/deal.II/base/mpi.h
> +      ~MPI_InitFinalize() = default;
It was because of a warning from nvcc but I don't remember which version of nvcc I was using.

2024-04-09 12:15 UTC, Rombur commented
@masterleinad `ping`

2024-04-09 12:46 UTC, masterleinad approved these changes

2024-04-09 12:46 UTC, merged