Add Functions::FunctionUnitToReal.
dealii/dealii pull request #15838
Opened 2023-08-04 10:05 UTC by simonsticko

That transforms a function from real to real space to a function from reference space to reference space.

Opened to continue a feature discussion on the mailing list:

https://groups.google.com/g/dealii/c/FONV6StZZus

2023-08-18 13:35 UTC, bangerth requested changes

2023-08-18 13:35 UTC, bangerth commented on include/deal.II/base/function_unit_to_real.h
> +   * Wrapper class for transforming a function from real to unit space.
Can you provide some more context in the description of this class what it does?

2023-08-18 13:35 UTC, bangerth commented on include/deal.II/base/function_unit_to_real.h
> +    FunctionUnitToReal(const Function<dim> &function);
What is the role of this function? I think it would be useful to provide a formula that explains what this class actually does :-)

2023-08-18 13:35 UTC, bangerth commented on include/deal.II/base/function_unit_to_real.h
> +    SmartPointer<const Triangulation<dim>> triangulation;
Why not simply store the iterator, instead of breaking things down into its components?

2023-08-18 13:35 UTC, bangerth commented on include/deal.II/base/function_unit_to_real.h
> +    const MappingQ1<dim> mapping;
Does it make sense to allow arbitrary mappings?

2023-08-18 13:35 UTC, bangerth commented on source/base/function_unit_to_real.cc
> +// Copyright (C) 2015 - 2021 by the deal.II authors
```suggestion
// Copyright (C) 2023 by the deal.II authors
```

2023-08-18 13:35 UTC, bangerth commented on source/base/function_unit_to_real.cc
> +    fe_values.reinit(cell);
It is very expensive to re-create the `FEValues` object every time. I wonder whether it would be possible to cache it somehow?

2023-08-18 13:35 UTC, bangerth commented on source/base/function_unit_to_real.cc
> +    const Point<dim> &point_in_real_space = fe_values.quadrature_point(0);
```suggestion
    const Point<dim> point_in_real_space = fe_values.quadrature_point(0);
```

2023-10-31 20:17 UTC, bangerth commented
@simonsticko Ping?

2023-10-31 20:52 UTC, simonsticko commented
> @simonsticko Ping?

I could finish this, but do we think that this function is worth having in the library? There is a use case for this, but as discussed on the mailing list, this is a pretty poor idea, because it is very slow.

2023-10-31 21:01 UTC, bangerth commented
It's your choice. If you no longer think it's a generally useful addition, then let's close it.

2024-04-17 22:55 UTC, bangerth commented
@simonsticko Any thoughts about this PR?

2024-04-18 05:33 UTC, simonsticko commented
I do not think this is a good idea. Having this functionality encourages use of something that has very poor performance. I should have closed this earlier.

2024-04-18 05:33 UTC, closed without merging