Move DoFTools templates to templates.h header file
dealii/dealii pull request #16485
Opened 2024-01-17 20:59 UTC by tamiko

Move all templates from `dof_tools.cc` to `dof_tools.templates.h`. In addition
this PR gets rid of a number of anonymous namespaces that we try to avoid in
header files.

  - DoFTools: move templates to dof_tools.templates.h
  - dof_tools.template.h: remove anonymous namespaces

In reference to #16484

2024-01-17 21:00 UTC, tamiko commented
/rebuild

2024-01-17 21:45 UTC, marcfehling approved these changes

2024-01-18 15:44 UTC, bangerth requested changes

2024-01-18 15:44 UTC, bangerth commented on include/deal.II/dofs/dof_tools.templates.h
> +               const ComponentMask             &component_mask)
I don't see the point to have these sorts of functions in a `.templates.h` file. We know exactly what kinds of arguments these functions could possibly be instantiated for, and we do. There is no reason anyone could need these functions in a file that can be `#include`d.

2024-01-18 17:26 UTC, closed without merging