FE_NedelexSZ: Find hanging edges rework
dealii/dealii pull request #16644
Opened 2024-02-14 10:29 UTC by kinnewig

This is a follow-up to #16304
The first pull request does not cover the case where five or more cells are adjacent to one edge. 

### Problem
Let us consider the following setting
![Hanging-Edge](https://github.com/dealii/dealii/assets/35812030/ffe74fd4-5ed3-4244-9b72-7df21f1bca01)

We still encounter a sign conflict (because the cells opposite to the coarse cell do not notice that they have one hanging edge).

### Proposed Solution
To overcome this problem, we pre-compute an edge-to-cell map to quickly access all cells adjacent to a specific edge. The edge-to-cell map itself is stored and used inside of FE_Nedelec_SZ.
The pre-computation of the edge-to-cell map is triggered by the call `compute_hanging_node_constraints()`. Thereby, everything stays the same for the user. 

### (Optional) Test Case
I also designed a test case to verify that hanging edges are handled correctly in the above-explained setting. 
In the picture-norm, one can see nicely that the hanging edge is handled correctly. But for some reason, I can not see the same behavior when using get_function_values(). I still included the test. Someone may have an idea of what the problem is.
Here is the plot of the solution. On the left-hand side is the solution with a sign conflict at the edge in the center, and on the right-hand side is the solution without a sign conflict at the center.
![hanging-edge-test](https://github.com/dealii/dealii/assets/35812030/6aff3869-c34f-4745-86fc-72316d7f8edb)

But we could also drop this test entirely since the problem of addressing the sign conflict on a hanging edge is also covered by the test `fe_nedelec_sz_hanging_nodes_convergence`. The only difference between the here proposed test and `fe_nedelec_sz_hanging_nodes_convergence` is that this test also covers the case where seven cells share one edge, but for the implementation, it does not make any difference how many cells share one edge.

2024-03-20 08:10 UTC, kronbichler commented
/rebuild

2024-03-20 09:25 UTC, kronbichler reviewed
Thank you for this PR, and sorry for letting it sit around without review for such a long time.

I have a few technical comments as outlined below. I also have a general question I would like to discuss: This moves an expensive data structure related to the global mesh into the finite element class. I hesitate with this design because it blurs one of the design principles in the library, which makes the finite element classes stateless in terms of the underlying grid, and have the `DoFHandler` class taking care of the description of the degrees of freedom. I realize that the Nedelec spaces are complicated in this regard because of the sign change and other factors that affect the value of shape function in related to the global triangulation and how the mesh elements are actually aligned. In other words, I have not solution worked out for this concept yet, and would like to discuss some options with you:
- Possible technical problems aside, would you think that moving the information you request to the triangulation class (my favorite) or DoFHandler class and query it from there would be an option? After all, it seems you only construct information about the mesh that is per se not related to any finite element.
- The question is at which point this information should be computed. Computing it all the time might be expensive in terms of memory (because the grid memory would probably more than double when all line-to-cell and vertex-to-cell relations would be pre-computed). Computing on demand might work, keeping a data structure within `Triangulation` that gets filled upon first call to a `GridTools` function or the one here and making sure that any change in the grid would invalidate the stored files.
- Now coming to the technical level, if the Triangulation class were to store this information, do you see what would be necessary for the respective function to access it?

Things might be more involved than I anticipate, so feel free to correct me or suggest other possibilities you see at this stage.

I am happy to help with these questions. If you find it useful, we could also arrange a zoom meeting in case things need to be weighed against each other.

2024-03-20 09:25 UTC, kronbichler commented on source/fe/fe_nedelec_sz.cc
> +      GeometryInfo<dim>::lines_per_cell));
Given this complicated setup, could `Table<2, std::set<typename Triangulation<dim, spacedim>::active_cell_iterator>` be a more appropriate data structure? It seems you only need the access via the pair  `active_cell_index / line_index_within_cell`, so a 2D array seems most efficient. (Keeping the efficiency of `std::set` aside, but that is not related to this PR.)

2024-03-20 09:25 UTC, kronbichler commented on source/fe/fe_nedelec_sz.cc
> +              // compute_haging_node_constraints(). Thereby, everything stays
```suggestion
              // compute_hanging_node_constraints(). Thereby, everything stays
```

2024-03-25 09:49 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +            adjacent_cells_to_vertex_1 = vertex_to_cell[vertex_1];
done!

2024-03-25 09:49 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +    vertex_to_cell =
done!

2024-03-25 09:49 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +              // compute_haging_node_constraints(). Thereby, everything stays
done!

2024-03-25 10:30 UTC, kinnewig commented
First, thank you for the feedback! As this is quite specific, I understand that it takes some time to review.

> - Possible technical problems aside, would you think that moving the information you request to the triangulation class (my favorite) or DoFHandler class and query it from there would be an option? After all, it seems you only construct information about the mesh that is per se not related to any finite element.

I am not that familiar with the triangulation class since I have not directly worked on it yet. But I will try to move the `line_to_cell_map` into it.

> - The question is at which point this information should be computed. Computing it all the time might be expensive in terms of memory (because the grid memory would probably more than double when all line-to-cell and vertex-to-cell relations would be pre-computed). Computing on demand might work, keeping a data structure within Triangulation that gets filled upon first call to a GridTools function or the one here and making sure that any change in the grid would invalidate the stored files.

At the moment, the `line_to_cell_map` is computed whenever `compute_hanging_node_constraints()` is called. 
I guess this is a good approach since this map is only necessary in the presence of hanging nodes. And one must compute the corresponding constraints. Otherwise, this can not work. Moreover, `compute_hanging_node_constraints()` has to be called whenever the underlying triangulation is modified. 
The only downside I see is that if we move the line_to_cell_map() into the triangulation, the function to trigger the computation of that map must be public so it can be called from within the DoF handler. 

> - Now coming to the technical level, if the Triangulation class were to store this information, do you see what would be necessary for the respective function to access it?

This is a bit more tricky for me since, as mentioned above, I am not that familiar with the triangulation class yet. Sure, I have some ideas on how to do that, but I am not sure what would fit best into deal.II. The simplest way is to make this map publicly accessible. And if that is not desired, I could create a class that is a friend of the triangulation class and mark the `line_to_cell_map` as protected.

2024-07-17 09:33 UTC, kronbichler commented
Let me move the milestone to the next release; I think we have a plan, but @kinnewig is busy with other topics at this point as far as I know.

2025-07-03 14:25 UTC, Rombur commented
This won't make it for the current release. I'll move the milestone to the next release

2025-11-12 13:51 UTC, kinnewig commented
Over a year ago, I discussed with @kronbichler how to refactor this pull request, and I have finally found the time to do it now. So, this is a complete restructure of the pull request.

To find the hanging edges described above, we need a map that indicates, given a specific edge, which cells are adjacent to that edge. I moved the computation of that map from the FE_NedelecSZ class to the triangulation.

However, it is challenging to gain an overview of the Triangulation class, so please let me know if there is anything that does not fit into deal.II as it currently stands.
One thing I am not sure about is the best way to implement a trigger to compute the `line_to_adjacent_cell_map`. Currently, I have added a function `void prepare_line_to_adjacent_cells_map()` that triggers the computation. Another approach could be to add a new field to the constructor of the triangulation that triggers the computation of the `line_to_adjacent_cell_map`. So, I am open to ideas.

Moreover, the `line_to_adjacent_cell_map` is dropped on refinement, as it has to be recomputed after the grid has changed. 

I also adapted the test, so it now works as intended.

2025-11-12 13:52 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +      GeometryInfo<dim>::lines_per_cell));
I used `Table<2, std::set<typename Triangulation<dim, spacedim>::active_cell_iterator> ` in the refactored version.

2026-06-07 06:33 UTC, kinnewig commented
If there is anything left to do here, please let me know!
As far as I am concerned, this can be merged.

2026-06-08 03:29 UTC, bangerth requested changes
Thanks for following @kronbichler 's suggestion of moving the computation into the triangulation. This is certainly correct because I can see a finite element being used for two DoFHandlers/Triangulations at the same time. I think this information must live in the triangulation, or a structure such as `GridToolsCache` that caches this information.

Most of my comments are not particularly complicated. The two that might require more work are:
* Moving the computation of the map into `GridTools` given that there is already a similar function.
* Using a more memory-efficient data structure than `std::set` at the innermost level.

I would be ok if we deferred these two points to a later time and just opened issues for them -- this is a bug fix, and we can optimize things later on separately.

2026-06-08 03:29 UTC, bangerth commented on include/deal.II/grid/tria.h
> +  prepare_line_to_adjacent_cells_map();
Let's call this function `compute_...()`. I think that more accurately says what the function does, which isn't just to *prepare* but actually *build* the map.

In the documentation, could you mention that the information this class computes can be accessed via `TriaAccessor::get_cells_adjacent_to_line()`?

2026-06-08 03:29 UTC, bangerth commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
Let's do it like this:

```suggestion
   * The table stores the neighboring cells for each line.
   * This allows for quick access to the adjacent cells,
   * given the cell and the line number.
   * 
   * This map is destroyed upon mesh refinement, and can be
   * rebuilt by calling compute_line_to_adjacent_cells_map(). If
   * that function is not called, the map does not exist.
   */
  std::optional<Table<2, std::set<active_cell_iterator>>> line_to_adjacent_cells_map;
```

2026-06-08 03:29 UTC, bangerth commented on include/deal.II/grid/tria_accessor.h
> +   * 'Triangulation::prepare_line_to_adjacent_cells_map()' has to be called
doxygen will automatically link and mark up correctly:

```suggestion
   * Triangulation::prepare_line_to_adjacent_cells_map() has to be called
```

2026-06-08 03:29 UTC, bangerth commented on source/dofs/dof_tools_constraints.cc
> +      tria.prepare_line_to_adjacent_cells_map();
This is expensive and you're calling this function for all elements whether or not they need it. I wonder if it would be easier if we introduced a virtual `FiniteElement::prepare_for_hanging_node_constraints()` function that is unconditionally called here and that gets the `DoFHandler` as argument. The default implementation of that function does nothing. The `FE_NedelecSZ` class overloads the function and calls `prepare/compute_line_to_adjacent_map()`.

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                if (!cell->face(f)->at_boundary())
This is tangential to the question you're trying to answer in this patch, but a face can be at the boundary and still the face's lines can have neighbors. Think about a coarse mesh that consists of 3 cells arranged in the shape of an L. Or also the geometry in this PR with 5 or 7 cells where you remove one of the cells.

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                        [GeometryInfo<dim>::face_to_cell_lines(f, m)] = true;
Something is wrong here. The arguments to `face_to_cell_lines()` are a face and a line. But `m` loops over the *vertices* of a face. This presumably works here because a face of a hypercube has 4 vertices and 4 lines, but it is conceptually not right.

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                    continue;
You're inside a loop over `line`, but the condition here does not reference `line` at all -- in other words, the `if` condition is a loop invariant. This suggests that you could just guard the whole loop with this `if` condition.

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                  int cell_level = cell->level();
```suggestion
                  const int cell_level = cell->level();
```

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                    GeometryInfo<dim>::line_to_cell_vertices(line, 1);
```suggestion
                  const unsigned int v0_loc =
                    GeometryInfo<dim>::line_to_cell_vertices(line, 0);
                  const unsigned int v1_loc =
                    GeometryInfo<dim>::line_to_cell_vertices(line, 1);
```

2026-06-08 03:29 UTC, bangerth commented on source/fe/fe_nedelec_sz.cc
> +                  // get the global vertexc indices
```suggestion
                  // get the global vertex indices
```

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +  if (dim == 3)
```suggestion
  if constexpr (dim == 3)
```

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +  if (dim == 3)
I think it might be useful to state both in the documentation of this function and of the `TriaAccessor` function that the information will only be built if `dim==3`.

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +        GridTools::vertex_to_cell_map(*this);
Since there is already this function, would it make sense to move the whole functionality below into a corresponding function in `GridTools` as well?

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +              GeometryInfo<dim>::line_to_cell_vertices(line, 1));
```suggestion
            const unsigned int vertex_0 = cell->vertex_index(
              GeometryInfo<dim>::line_to_cell_vertices(line, 0));
            const unsigned int vertex_1 = cell->vertex_index(
              GeometryInfo<dim>::line_to_cell_vertices(line, 1));
```

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +    line_to_adjacent_cells_map.clear();
If you used a `std::optional` as suggested, then you can just call `line_to_adjacent_cells_map.reset()`.

2026-06-08 03:29 UTC, bangerth commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
Separately, I suspect that @drwells is not going to like this data structure. That is a *lot* of `std::set` objects, each of which is not very memory efficient.

How about you make this a `boost::small_vector<active_cell_iterator,4>` instead, on the assumption that in most parts of a mesh, there will be 4 cells adjacent to an edge, and if there are more, then we only have to allocate dynamically for those edges? Or perhaps set the limit to 6 instead of 4, to stay on the safe side?

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +        this->n_active_cells(), GeometryInfo<dim>::lines_per_cell);
This is right for hex meshes. But it's inefficient for other reference cell types. How about this?

```suggestion
      this->line_to_adjacent_cells_map.reinit(
        this->n_active_cells(), 
        (is_mixed_mesh() ?
        GeometryInfo<dim>::lines_per_cell : // err on the safe side: choose the largest number of lines per cell
        get_reference_cells()[0].n_lines()) // choose the right number of  lines per cell for the mesh type used
        );
```

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria.cc
> +              std::inserter(
If you went with the `boost::small_vector`, you'd have to remove the entries that are already in the table from the set first so that you don't store duplicates, and then sort.

2026-06-08 03:29 UTC, bangerth commented on source/grid/tria_accessor.cc
> +    return std::set<TriaActiveIterator<CellAccessor<dim, spacedim>>>();
I must admit that I don't understand the comment. I would very much prefer if this function threw an error if the table has not been built. Why is that not possible?

2026-06-08 03:29 UTC, bangerth commented on tests/fe/fe_nedelec_sz_hanging_edge.cc
> + */
We changed our copyright header. Can you take the current one from another test?

2026-06-08 03:29 UTC, bangerth commented on tests/fe/fe_nedelec_sz_hanging_edge.cc
> +
Please add a comment to the test that explains what it does.

2026-06-08 03:39 UTC, bangerth commented
I have one other comment: We have tests that check about the correctness of hanging node constraints in the following way:
* You create a mesh that has hanging nodes, and attach a `DoFHandler` with a finite element to it.
* You create a solution vector.
* You write random values into the solution vector. At this point, the values at hanging nodes do not contain the correct, constrained values.
* Then you call `make_hanging_node_constraints()` and call `constraints.distribute(solution_vector)`. At this point, you should have the correct, constrained values at all hanging nodes.
* If this is so, then the finite element field that is associated with the solution vector must have the correct continuity requirements at all faces. For example, for `FE_Q` elements, the field must be continuous. For the Nedelec elements, its *tangential component* must be continuous. 
* The test then checks that the latter is true.

Historically, we have implemented the check by hand. Today, we have `FEInterfaceValues` that could make that a bit more elegant: You get the *jump* of the finite element field across a face (i.e., all faces of the mesh) and make sure that the jump is zero (for `FE_Q`) or its tangential component is zero (for the Nedelec elements).

2026-06-08 03:39 UTC, bangerth commented
I don't know whether you have the time to implement any of this, of course. We will appreciate whatever time you can offer!

2026-06-08 22:08 UTC, drwells commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
`boost::small_vector<T, 6>` is a good choice! Jokes aside - code that works is always infinitely better than code that doesn't work (same goes for existing vs. not existing). Even if we commit something with `std::set` we've made progress.

2026-06-09 00:02 UTC, bangerth commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
Yes, indeed. As said above, I would be very happy to merge with `std::set` and worry about optimization at a later time.

2026-06-10 08:25 UTC, lukasdreyer commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
Is there a use for all line-adjacent cells in other cases? Otherwise, for this specific usecase, precomputing line_neighbor_is_coarser might be enough. (Or we could even precompute edge_sign as needed in FE_nedelec). Both of these only need to save one bool per line instead of a set of iterators.

2026-06-10 14:58 UTC, bangerth commented on include/deal.II/grid/tria.h
> +  Table<2, std::set<active_cell_iterator>> line_to_adjacent_cells_map;
We haven't had a need to store this in `Triangulation` in the 28 years this class has existed, so my expectation is that it's not used *frequently* in algorithms. That doesn't mean that people don't use these sorts of maps -- like many of the other things that exist in `GridTools` and that one can then store on the side. So my preference would have been to just not store it in the triangulation at all and let that place store it that actually uses it. That just turns out to be quite awkward in the current context, but I don't think I'd like to store more than necessary in the triangulation and so the current approach of computing only on demand is ok with me.

Storing one bit per edge is a different story. I think that is something I could support.

2026-06-15 21:17 UTC, bangerth commented
@kinnewig Might I politely ask whether you have time to address this? I think it would be nice to put this into the upcoming release, and if you don't have time (which I fully understand), then I can see whether I can take this over.

2026-06-18 13:43 UTC, kinnewig commented on include/deal.II/grid/tria.h
> +  prepare_line_to_adjacent_cells_map();
Done

2026-06-18 13:48 UTC, kinnewig commented on source/dofs/dof_tools_constraints.cc
> +      tria.prepare_line_to_adjacent_cells_map();
Yes, that function is quite expensive. That is definitely a good idea. 
However, this requires more work than I can offer at the moment.

2026-06-18 13:51 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +                if (!cell->face(f)->at_boundary())
Thank you for pointing this out! 
I removed the check `if (!cell->face(f)->at_boundary())`

2026-06-18 13:56 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +                        [GeometryInfo<dim>::face_to_cell_lines(f, m)] = true;
Fixed.

2026-06-18 13:57 UTC, kinnewig commented on source/fe/fe_nedelec_sz.cc
> +                    continue;
Done!

2026-06-18 14:08 UTC, kinnewig commented on source/grid/tria.cc
> +  if (dim == 3)
I added a remark that this is only implemented for `dim==3` at both places.

2026-06-18 14:20 UTC, kinnewig commented on source/grid/tria_accessor.cc
> +    return std::set<TriaActiveIterator<CellAccessor<dim, spacedim>>>();
I tried to always throw an error here instead, but then that error always occurs when creating a `FE_NedelecSZ` object, as this part is always called on an empty triangulation first.
But I have to admit, this may not be the best workarround.

2026-06-18 14:39 UTC, kinnewig commented on tests/fe/fe_nedelec_sz_hanging_edge.cc
> +
Done

2026-06-18 14:40 UTC, kinnewig commented on tests/fe/fe_nedelec_sz_hanging_edge.cc
> + */
Updated!

2026-06-18 14:52 UTC, kinnewig commented on source/grid/tria.cc
> +        GridTools::vertex_to_cell_map(*this);
I see no reason not to move this part into `GridTools`. Actually, I think that is a good idea.

However, as you have written above, this requires more work. And unfortunately, I can not offer this amount of work before the next release.

2026-06-18 15:05 UTC, kinnewig commented
Please excuse my late answer, I caught a cold... and my timetable was already swamped before that.

However, I tried to address all the points above, which required not too much work. 

I also find the other suggestions (replace std::set with something more efficient and move the computation of the map into GridTools) good. But I am missing the time for that at the moment.

So please feel free to implement those changes, and I will try to help as well as I can.

2026-06-18 16:27 UTC, bangerth commented
There's still a couple of build errors:
```
/Users/jenkins/jenkins/workspace/dealii-osx_PR-16644/source/grid/tria.cc:15920:37: error: expected ';' after expression
 15920 |   line_to_adjacent_cells_map.reset()
       |                                     ^
       |                                     ;
/Users/jenkins/jenkins/workspace/dealii-osx_PR-16644/source/grid/tria.cc:12876:40: error: no member named 'reinit' in 'std::optional<dealii::Table<2, std::set<dealii::TriaActiveIterator<dealii::CellAccessor<3, 3>>>>>'
 12876 |       this->line_to_adjacent_cells_map.reinit(
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-16644/build/source/grid/tria.inst:91:17: note: in instantiation of member function 'dealii::Triangulation<3, 3>::compute_line_to_adjacent_cells_map' requested here
   91 |  template class Triangulation< 3 ,  3 >;
      |                 ^
/Users/jenkins/jenkins/workspace/dealii-osx_PR-16644/source/grid/tria.cc:12909:17: error: type 'std::optional<Table<2, std::set<active_cell_iterator>>>' (aka 'optional<Table<2, set<TriaActiveIterator<CellAccessor<3, 3>>>>>') does not provide a call operator
 12909 |                 line_to_adjacent_cells_map(cell->active_cell_index(), line),
       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

I appreciate you working through these items. I think once this compiles and has been squashed into self-contained commits, let's merge. I will then open a bunch of issues that cover the improvements pointed out above, but these can wait for another time -- I see this PR primarily as a bug fix.

2026-06-23 03:24 UTC, bangerth commented
We're getting core dumps on the following tests :-(

[projectroot.tests.fe.fe_nedelec_sz_non_rect_facedebug.serial.fe/fe_nedelec_sz_non_rect_face.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_non_rect_facedebug/serial/fe_fe_nedelec_sz_non_rect_face_debug/)
[projectroot.tests.fe.fe_nedelec_sz_divergence_theorem_hanging_nodesdebug.serial.fe/fe_nedelec_sz_divergence_theorem_hanging_nodes.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_divergence_theorem_hanging_nodesdebug/serial/fe_fe_nedelec_sz_divergence_theorem_hanging_nodes_debug/)
[projectroot.tests.fe.fe_nedelec_sz_hessian_divergence_theoremdebug.serial.fe/fe_nedelec_sz_hessian_divergence_theorem.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_hessian_divergence_theoremdebug/serial/fe_fe_nedelec_sz_hessian_divergence_theorem_debug/)
[projectroot.tests.fe.fe_nedelec_sz_face_orientationdebug.serial.fe/fe_nedelec_sz_face_orientation.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_face_orientationdebug/serial/fe_fe_nedelec_sz_face_orientation_debug/)
[projectroot.tests.fe.fe_nedelec_sz_gradient_divergence_theoremdebug.serial.fe/fe_nedelec_sz_gradient_divergence_theorem.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_gradient_divergence_theoremdebug/serial/fe_fe_nedelec_sz_gradient_divergence_theorem_debug/)
[projectroot.tests.fe.fe_prolongation_nedelec_szdebug.serial.fe/fe_prolongation_nedelec_sz.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_prolongation_nedelec_szdebug/serial/fe_fe_prolongation_nedelec_sz_debug/)
[projectroot.tests.fe.fe_nedelec_sz_face_valuesdebug.serial.fe/fe_nedelec_sz_face_values.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_face_valuesdebug/serial/fe_fe_nedelec_sz_face_values_debug/)
[projectroot.tests.fe.fe_nedelec_sz_hanging_nodes_convergencedebug.serial.fe/fe_nedelec_sz_hanging_nodes_convergence.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_hanging_nodes_convergencedebug/serial/fe_fe_nedelec_sz_hanging_nodes_convergence_debug/)
[projectroot.tests.fe.get_fe_by_name_01debug.serial.fe/get_fe_by_name_01.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.get_fe_by_name_01debug/serial/fe_get_fe_by_name_01_debug/)
[projectroot.tests.fe.fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundarydebug.serial.fe/fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundary.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundarydebug/serial/fe_fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundary_debug/)
[projectroot.tests.numerics.project_bv_curl_conf_05debug.serial.numerics/project_bv_curl_conf_05.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.numerics.project_bv_curl_conf_05debug/serial/numerics_project_bv_curl_conf_05_debug/)
[projectroot.tests.fe.fe_conformity_dim_3_fe_nedelec_szdebug.serial.fe/fe_conformity_dim_3_fe_nedelec_sz.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_conformity_dim_3_fe_nedelec_szdebug/serial/fe_fe_conformity_dim_3_fe_nedelec_sz_debug/)
[projectroot.tests.fe.fe_nedelec_sz_hanging_edgedebug.serial.fe/fe_nedelec_sz_hanging_edge.debug](https://ci.tjhei.info/job/dealii-serial/job/PR-16644/27/testReport/junit/projectroot.tests.fe.fe_nedelec_sz_hanging_edgedebug/serial/fe_fe_nedelec_sz_hanging_edge_debug/)

2026-06-24 14:47 UTC, kinnewig commented
The remaining error is nasty... It only occurs when deal.II is build in serial. I will take a closer look tomorrow.

2026-06-29 12:36 UTC, bangerth commented
I take it you fixed the issue and that this is ready?

2026-06-29 13:06 UTC, kinnewig commented
Yes, the issue is fixed, and it is ready to be merged.

2026-06-30 18:00 UTC, bangerth approved these changes

2026-06-30 18:03 UTC, bangerth commented
I will merge this, and deprecate the new function `TriaAccessor` again right away (not early-deprecate) in view of the fact that I think we should move the expensive data structure to the element itself -- see #19905. In other words, the function will be available in 9.8 and be removed again right away. In an ideal world, I would implement the resolution of #19905 right away, but I don't think I have the time before the release and so making sure that the function should not be used seems like the most reasonable approach.

(And to repeat why I want this PR in the release: It fixes an actual bug.)

2026-06-30 18:03 UTC, merged