Fix unintended terminate in gmsh-API version of read_msh
dealii/dealii pull request #16714
Opened 2024-03-04 22:44 UTC by simonsticko

The gmsh-api version of GridIn::read_msh uses a throw statement without specifing an exception. The intention is cleary to throw any exception but the standard specifies that doing this outside of a catch block should lead to std::terminate being called. Specify an exception to fix this and add a test that covers this part of the function.

2024-03-05 00:41 UTC, Rombur submitted a review, later dismissed

2024-03-05 00:41 UTC, Rombur commented
/rebuild

2024-03-05 12:34 UTC, masterleinad commented
In my opinion, it would be better to only catch exceptions from the call to 
```
Patterns::Tools::to_value(name, id_names);
```
and otherwise don't use exceptions for control flow but just replace `throw;` with `boundary_id = physical_tag;`.

2024-03-06 02:15 UTC, bangerth submitted a review, later dismissed

2024-03-06 02:19 UTC, bangerth reviewed
On looking through this again, I agree with @masterleinad . It is strange to see the throw immediately next to the catch. I think that the code would be easier to read if you renamed `throw_anyway` by something like `found_unrecognized_tag` and instead of throwing just copy the code from the `catch` block.

While you're there, would you mind adding a comment somewhere that explains that the `throw` can happen in the `Patterns::Tools::to_value()`? Until @masterleinad pointed it out, I had not realized that there is a second place in the `try` block where the exception could be coming from.

2024-03-11 13:15 UTC, masterleinad requested changes
Please address https://github.com/dealii/dealii/pull/16714#issuecomment-1978674781.

2024-03-11 17:22 UTC, masterleinad approved these changes

2024-03-15 19:58 UTC, merged

2024-03-19 09:44 UTC, kronbichler commented
The test is failing with the address sanitizer run, https://cdash.dealii.org/test/15962098. It seems the error happens inside `gmsh::initialize` (some container overflow, but I honestly don't fully understand it, because it reads a piece of 24 bytes at a distance of 72 bytes in an array of size 96 bytes, so valid?), but that call should also happen on the other gmsh tests. @simonsticko do you have an idea what could go wrong,

2024-03-19 18:34 UTC, simonsticko commented
>  @simonsticko do you have an idea what could go wrong,

No. I don't understand this at all. The error is before we pass any data to gmsh.

2024-03-20 01:01 UTC, bangerth commented
Do we have a backtrace?