Colorize hyper rectangle with simplices
dealii/dealii pull request #16713
Opened 2024-03-04 13:25 UTC by nmuch

2024-03-05 06:00 UTC, peterrum approved these changes
/rebuild

2024-03-05 14:54 UTC, kronbichler approved these changes

2024-03-06 03:46 UTC, bangerth requested changes

2024-03-06 03:46 UTC, bangerth commented on source/grid/grid_generator.cc
> +                             0.01 * (std::abs(p2[i] - p1[i]) / repetitions[i]));
This is not the right way to approach this. `p2[i] - p1[i]` is a quantity that depends on the magnitude of the points chosen as inputs, so it has physical units. But `eps=10` does not. You need to start with an eps that has the right order of magnitude. Alternatively, you could start with `eps=infinity`, i.e., `eps=std::numeric_limits<double>::max()`.

2024-03-06 09:32 UTC, kronbichler approved these changes
Thanks for the fix, and thanks to @bangerth for noticing!

2024-03-06 12:45 UTC, masterleinad approved these changes

2024-03-06 13:19 UTC, bangerth approved these changes

2024-03-06 13:20 UTC, bangerth commented
This looks right now. Thank you!

It would be nice to have a test that checks this. Do you know how to clone existing tests and add those?

2024-03-08 14:54 UTC, kronbichler approved these changes

2024-03-08 14:54 UTC, merged