SolverGMRES: Skip work if x is all zero
dealii/dealii pull request #16761
Opened 2024-03-19 20:52 UTC by kronbichler

Fixes #14619.

2024-03-20 01:00 UTC, bangerth requested changes

2024-03-20 07:25 UTC, kronbichler commented on include/deal.II/lac/solver_gmres.h
> +            }
Excellent suggestion! Will do so.

2024-03-20 11:23 UTC, peterrum approved these changes

2024-03-21 21:53 UTC, bangerth approved these changes

2024-03-21 21:53 UTC, merged