MappingCartesian: Some performance improvements
dealii/dealii pull request #16830
Opened 2024-04-01 19:26 UTC by kronbichler

Looking at the performance case in https://github.com/dealii/dealii/issues/16796#issuecomment-2027794215 I realized that some internal functions in `MappingCartesian` are somewhat wasteful, performing unnecessary divisions or doing operations for one point at a time in `transform_real_to_unit_cell`. Improve those places and test the new code.

2024-04-01 21:13 UTC, drwells requested changes
Nice! I have some minor comments.

2024-04-01 21:13 UTC, drwells commented on doc/news/changes/minor/20240401Kronbichler
> +Improved: Several functions in MappingCartesians have been carefully rewritten
```suggestion
Improved: Several functions in MappingCartesian have been carefully rewritten
```

2024-04-01 21:13 UTC, drwells commented on doc/news/changes/minor/20240401Kronbichler
> +for better performance, e.g. by avoiding divisions and making use of recurring
```suggestion
for better performance, e.g., by avoiding divisions and making use of recurring
```

2024-04-01 21:13 UTC, drwells commented on tests/mappings/mapping_cartesian_points_real_to_unit.cc
> +
```suggestion
```

2024-04-02 07:09 UTC, kronbichler commented
@drwells thank you for the suggestsions, updated.

2024-04-02 16:33 UTC, bangerth reviewed
Yes, nice!

2024-04-02 16:33 UTC, bangerth commented on source/fe/mapping_cartesian.cc
> +    DEAL_II_NOT_IMPLEMENTED();
This does not output the controlling condition `dim==spacedim`. Would you mind writing this as
```
  Assert (dim==spacedim,
               ExcNotImplemented());
```
? Same below.

2024-04-02 16:33 UTC, bangerth commented on source/fe/mapping_cartesian.cc
> +    DEAL_II_NOT_IMPLEMENTED();
Here

2024-04-02 16:54 UTC, masterleinad approved these changes

2024-04-04 07:53 UTC, kronbichler commented
@drwells any additional comments here?

2024-04-04 14:44 UTC, drwells approved these changes

2024-04-04 16:39 UTC, merged