Epetra vector access operator
dealii/dealii pull request #16880
Opened 2024-04-12 14:03 UTC by pcafrica

This PR should solve #16877.

2024-04-12 22:54 UTC, bangerth approved these changes
Thank you!

2024-04-12 22:54 UTC, bangerth requested changes
Let me retract the approval -- this is ok to merge if we can find a different place for the `using` declaration.

2024-04-13 11:27 UTC, pcafrica commented on include/deal.II/lac/trilinos_epetra_vector.h
> +      using value_type = double;
Hi @bangerth, I'm not sure if I got your comment correctly.

I just followed the same pattern used in other similar classes (Tpetra Vector, TrilinosWrappers::MPI::Vector and so on).

What exactly do you mean by choosing a different namespace?

2024-04-13 11:29 UTC, pcafrica commented on include/deal.II/lac/trilinos_epetra_vector.h
> +      using value_type = double;
Do you just want to drop aliases from the `internal` namespace and leave them only in the main `Vector` class?

2024-04-16 03:17 UTC, bangerth commented on include/deal.II/lac/trilinos_epetra_vector.h
> +      using value_type = double;
What I meant is that having
```
  namespace EpetraWrappers {
    namespace internal {
      using value_type = double;
```
leaves a generically names type `value_type` in a namespace that is not clearly associated with the `Vector` class. It is perhaps true that *all* of the `EpetraWrappers` classes use `double` as their value type, but the point of the `value_type` you declare here is to support one specific class, and that should be made clear by either choosing a name that makes that obvious, or put it into a namespace that is clearly associated with the `Vector` class.

The ideal namespace, of course, is the class itself. So if there was a way to redirect all of the places where you use the `typdef` to the `Vector::value_type` type, that would be ideal.

Same for the other typedef (`size_type`).

2024-04-16 07:54 UTC, pcafrica commented on include/deal.II/lac/trilinos_epetra_vector.h
> +      using value_type = double;
Oh, I see your point. Would something like [this](c356f59de2a3754d64d8212bfa9d701cb5d04d51) work?

I'm noticing a similar pattern in other places (e.g. in `trilinos_vector.h` and `trilinos_tpetra_vector.h`). If my proposed solution is ok, I'll take care of propagating the modification there.

2024-04-16 20:30 UTC, bangerth approved these changes
Yes, this works. Thanks for working with me on this issue!

I'd be very happy to approve (separate) PRs if you wanted to fix this in other places as well!

2024-04-16 20:31 UTC, bangerth commented
Would you mind fix-up'ing the indent commit into the commit it is supposed to fix?

2024-04-16 22:15 UTC, pcafrica commented
> Would you mind fix-up'ing the indent commit into the commit it is supposed to fix?

Done!

2024-04-16 23:29 UTC, bangerth commented
/rebuild

2024-04-16 23:30 UTC, bangerth commented
Thank you -- good to go!

2024-04-17 02:22 UTC, merged