NonMatching::FEValues: accept CellAccessor
dealii/dealii pull request #16932
Opened 2024-04-27 21:32 UTC by peterrum

2024-05-01 01:43 UTC, drwells requested changes
Want to add a short test?

2024-05-01 01:43 UTC, drwells commented on include/deal.II/non_matching/fe_values.h
> +     * this function exists is so that one can use hp::FEValues for
```suggestion
     * this function exists is so that one can use NonMatching::FEValues for
```

2024-05-01 01:43 UTC, drwells commented on include/deal.II/non_matching/fe_values.h
> +      const unsigned int mapping_index = numbers::invalid_unsigned_int);
`q_index` and `mapping_index` do the same thing here as in `hp::FEValues`, right? Could you either cite that class or add some documentation for those two arguments?

2024-05-01 01:43 UTC, drwells commented on include/deal.II/non_matching/fe_values.h
> +           const unsigned int fe_index      = numbers::invalid_unsigned_int);
Same thing

2024-05-05 13:41 UTC, peterrum commented
> Want to add a short test?

@drwells Done!

2024-05-06 15:10 UTC, drwells approved these changes

2024-05-06 15:10 UTC, merged