fix_void_problem
dealii/dealii pull request #17488
Opened 2024-08-12 20:54 UTC by liyli0126

2024-08-12 20:58 UTC, tamiko requested changes

2024-08-12 20:58 UTC, tamiko commented on source/base/function_lib.cc
>                                        const unsigned int component) const
You need to add the `[[maybe_unused]]` attribute in the parameter list.

2024-08-12 20:58 UTC, tamiko commented on source/base/function_lib.cc
> +    [[mabe_unused]]component;
And simply remove the `(void)component` line.

2024-08-12 21:21 UTC, liyli0126 commented
I replaced a void cast with the more modern [[maybe_unused]]

This is working towards fixing #17247

2024-08-13 15:07 UTC, bangerth commented on source/base/function_lib.cc
> +    [[mabe_unused]]component;
This is the wrong place to add the attribute. You want to attach the attribute to the place where the variable is *declared*. So this should look as follows instead:
```
FourierCosineFunction<dim>::value(const Point<dim>  &p,
                                    [[maybe_unused]] const unsigned int component) const
  {
```
Can you change that here and elsewhere?

2024-08-27 21:41 UTC, closed without merging