Replaced void with maybe_unused
dealii/dealii pull request #17506
Opened 2024-08-12 22:20 UTC by hagiasophia1994

Mark potentially-unused variables with [[maybe_unused]] instead of saying (void)x; #17247

2024-08-12 22:41 UTC, tamiko requested changes

2024-08-12 22:41 UTC, tamiko commented on tests/matrix_free/matrix_vector_hessians_cells.cc
>        const auto &matrix_free, auto &dst, const auto &src, const auto &range) {
You can either just remove the parameter names here:
```suggestion
      const auto &, auto &, const auto &, const auto &) {
```
Or add a `[[maybe_unused]]` to all of the parameters:
```suggestion
      [[maybe_unused]] const auto &matrix_free, [[maybe_unused]] auto &dst, [[maybe_unused]] const auto &src, [[maybe_unused]] const auto &range) {
```

2024-08-12 22:41 UTC, tamiko commented on tests/matrix_free/matrix_vector_hessians_cells.cc
> +      const auto &matrix_free, auto &dst, const auto &src, [[maybe_unused]]const auto &range) {
This does not look right. You're not removing a `(void)range;` statement in the body of this lambda function.

2024-08-15 22:52 UTC, bangerth commented
If you have some time tomorrow, please talk to one of us about this pull request!

2024-08-27 21:45 UTC, closed without merging

2024-08-27 21:45 UTC, marcfehling commented
Superseded by #17617.