Arbitrary order quadrature on pyramids
dealii/dealii pull request #17578
Opened 2024-08-20 14:50 UTC by dominiktassilostill

Follow up to #17576. Relies on new functionalities introduced there. Based on the formals given [here](https://link.springer.com/article/10.1007/s10915-009-9334-9).

2024-08-20 15:19 UTC, peterrum commented on source/base/quadrature_lib.cc
> +  // Gauss-Legendre in x and y direction and Gauss-Jacobi in z direction
Could you add some references? Best to the class description!

2024-08-20 15:19 UTC, peterrum commented on source/base/quadrature_lib.cc
> +  // Gauss-Legendre in x and y direction and Gauss-Jacobi in z direction
Also we need a test.

2026-01-29 17:55 UTC, dominiktassilostill commented
Now relies on #19253

2026-02-03 19:07 UTC, drwells commented
I think you mean that other PR depends on this one, right? Can you rebase and fix the conflict?

2026-02-03 19:18 UTC, drwells commented
While we're here: to the best of my knowledge, we went with this definition of pyramids (vertices at +1/-1) because that's more common in the literature, though it is inconsistent with essentially everything else in deal.II. How much work would there be in translating other pyramid polynomials and quadrature rules to one whose base is the unit square? Do you think it would be worthwhile to change it now?

2026-02-17 16:30 UTC, dominiktassilostill commented
> While we're here: to the best of my knowledge, we went with this definition of pyramids (vertices at +1/-1) because that's more common in the literature, though it is inconsistent with essentially everything else in deal.II. How much work would there be in translating other pyramid polynomials and quadrature rules to one whose base is the unit square? Do you think it would be worthwhile to change it now?

Changing the polynomials and the quadrature rule should not be a problem, that only takes scaling some factors and adding some offsets. I think it would be more work to change the information in the reference cell and to find all the spots which implicitly assume the old vertex locations. But it will be easier to first merge the other code before changing the reference cell, as there it is clear how the polynomials transform.



> I think you mean that other PR depends on this one, right? Can you rebase and fix the conflict?

This PR relies on `Polynomials::jacobi_polynomial_derivative` which is added in #19253.

2026-02-25 16:23 UTC, drwells requested changes
Thanks. I have some comments on how to improve the tests.

2026-02-25 16:23 UTC, drwells commented on tests/simplex/qgauss_pyramid_01.cc
> +    }
Since this is a monomial, with a little bit of calculus we can derive the exact integral (i.e., for a function `x^i y^j x^k` and the reference Pyramid). Could you add that here and also print the errors so we know we are integrating these quantities exactly?

2026-02-25 16:23 UTC, drwells commented on tests/simplex/qgauss_pyramid_02.cc
> +  deallog << std::endl;
What is this test supposed to do? It looks like it just compares quadrature points and weights with known correct values. If so - why not just print out the points and weights and compare via the output file?

2026-04-27 14:22 UTC, dominiktassilostill commented on tests/simplex/qgauss_pyramid_01.cc
> +    }
It took a while, now the the results of the quadrature are compared to the exact solution. The error is not printed directly but it is only checked if an error is exceeded.

2026-04-27 14:23 UTC, dominiktassilostill commented on tests/simplex/qgauss_pyramid_02.cc
> +  deallog << std::endl;
This test only compared the values to the old implementation, so printing them out should do the same.

2026-06-05 22:35 UTC, bangerth commented
/rebuild

2026-06-16 03:14 UTC, bangerth commented
There is one failing test from this PR: https://ci.tjhei.info/job/dealii-serial/job/PR-17578/6/testReport/junit/projectroot.tests.simplex.polynomials_pyramid_01debug/serial/simplex_polynomials_pyramid_01_debug/

@dominiktassilostill @drwells Do you think we can still get this ready for this release?

2026-06-16 10:52 UTC, dominiktassilostill commented
@bangerth thanks for catching that.

The problem with the test was that the sequence of the quadrature points changed (in the previous version the z-direction was inverted), it is now fixed. By having the output twice, the diff shows that the test gives the same results in another order. The duplicated output is now also removed from the test.

2026-06-16 13:51 UTC, bangerth commented
Still no luck :-( https://ci.tjhei.info/job/dealii-serial/job/PR-17578/7/testReport/

2026-06-16 17:16 UTC, bangerth commented on include/deal.II/base/quadrature_lib.h
> + * Taken from @cite Bergot2010, the integration rules generates @p (n_points_1d)^3
```suggestion
 * Taken from @cite Bergot2010, the integration rules generate @p (n_points_1d)^3
```

2026-06-16 17:16 UTC, bangerth commented on source/base/quadrature_lib.cc
> +  QGauss<1> q_gauss(n_points_1D);
```suggestion
  const QGauss<1> q_gauss(n_points_1D);
```

2026-06-16 17:16 UTC, bangerth commented on tests/simplex/polynomials_pyramid_01.cc
> -    }
This is the mistakenly duplicated piece of code, right? I don't see any differences to the code above it. Or am I missing anything?

2026-06-16 17:16 UTC, bangerth commented on tests/simplex/qgauss_pyramid_02.cc
> +  deallog << std::endl;
Could you add a comment at the top of the test (like many other tests have) that explains in 2-3 lines what the test does? (Same also for the _01 test while you're there.)

2026-06-16 18:44 UTC, dominiktassilostill commented on tests/simplex/polynomials_pyramid_01.cc
> -    }
Yes, it is the same as the code above it. As I had to fix the test anyway I removed it.

2026-06-16 21:38 UTC, bangerth approved these changes

2026-06-16 21:38 UTC, bangerth commented
I'll let @drwells merge since he currently has a hold on this PR. I'm ok with it as is.

2026-06-16 21:48 UTC, bangerth commented
Separately, I was thinking about this PR during the lunch-time bike race today. Just like for triangles, these tensor product-type formulas are not optimal in the number of quadrature points, right?

Also: taking https://en.wikipedia.org/wiki/Gauss%E2%80%93Jacobi_quadrature as the basis, you use alpha=2 and beta=0 because the cross-sectional area of a pyramid decreases like (1-z)^2, right?

2026-06-17 12:03 UTC, kronbichler approved these changes

2026-06-17 14:37 UTC, drwells approved these changes

2026-06-17 14:37 UTC, merged

2026-06-19 17:08 UTC, dominiktassilostill commented
> Separately, I was thinking about this PR during the lunch-time bike race today. Just like for triangles, these tensor product-type formulas are not optimal in the number of quadrature points, right?

They are not optimal, using the techniques from [Witherden and Vincent](https://doi.org/10.1016/j.camwa.2015.03.017) should generate rules with less quadrature points. Hardcoding some of these for lower orders would be an option.

> Also: taking https://en.wikipedia.org/wiki/Gauss%E2%80%93Jacobi_quadrature as the basis, you use alpha=2 and beta=0 because the cross-sectional area of a pyramid decreases like (1-z)^2, right?

Yes, as `x` and `y` scale something like `x*(1-z)` and `y*(1-z)`, the overall factor of `(1-z)^2` results from the transformation.

2026-06-19 23:10 UTC, bangerth commented
Thanks for confirming, @dominiktassilostill! I put that into #19915.