Generalized read_msh to allow for comments
dealii/dealii pull request #17666
Opened 2024-09-05 17:48 UTC by mivaia

gmsh files generated by some software (Pointwise) include additional comment blocks in between the main sections in a .msh file. This is supported by the gmsh format but it was not supported by the dealii reader. This PR generalizes the reader to ensure it can adequately read such files. To do so, i had to refactor the way the mesh sections are read to allow to discard multiple comment blocks. A test was modified to verify comments could be added without affecting the reader.

2024-09-06 15:10 UTC, blaisb requested changes
Some initial comments, I will continue reviewing as soon as possible :)

2024-09-06 15:10 UTC, blaisb commented on source/grid/grid_in.cc
> +  int          n_entity_blocks = 1;
```suggestion
  unsigned int          n_entity_blocks = 1;
```
This could be an unsigned int, no reason for this to have a negative value.

2024-09-06 15:10 UTC, blaisb commented on source/grid/grid_in.cc
> +          int n_entity_blocks = 1;
Why redeclare n_entity_blocks that you had declared above? The above declaration is not used, is it necessary?

2024-09-06 15:10 UTC, blaisb commented on source/grid/grid_in.cc
> +          // std::map<unsigned int, unsigned int> vertex_counts;
This commented block of code is not necessary anymore, you have moved that elsewhere above

2024-09-06 21:31 UTC, bangerth commented
Out of curiosity, are the comments text between two successive lines of text that consist only of dashes? Is there a specification for how many dashes there have to be?

There are a lot of changes in this code that are not easy to decipher (though that may partly be github's fault). Have you considered simply reading in the entire file, stripping out comments, and then giving the rest to the existing function?

2024-09-08 13:53 UTC, blaisb commented
> Out of curiosity, are the comments text between two successive lines of text that consist only of dashes? Is there a specification for how many dashes there have to be?
> 
> There are a lot of changes in this code that are not easy to decipher (though that may partly be github's fault). Have you considered simply reading in the entire file, stripping out comments, and then giving the rest to the existing function?

The comments block are pretty much everywhere. However, you make a good point. We have not considered that and that would be a better idea to implement this without making major changes.


@mivaia , do you think  you could give this a go? Parse the entire file and throw away the comments block, putting it in a stream, and then using this with the regular function?

2024-09-09 02:46 UTC, bangerth commented
On 9/8/24 07:54, Bruno Blais wrote:
> The comments block are pretty much everywhere. However, you make a good point. 
> We have not considered that and that would be a better idea to implement this 
> without making major changes.

That was my thought. If the comments can be in a lot of places, you have to 
change the parsing in a lot of places. But if the comments always look the 
same, it's not so difficult to just "pre-process" the file in such a way that 
you remove the comments and then give the result to the existing code (that 
then no longer requires any changes at all).

2024-09-09 12:49 UTC, blaisb commented
> On 9/8/24 07:54, Bruno Blais wrote: The comments block are pretty much everywhere. However, you make a good point. We have not considered that and that would be a better idea to implement this without making major changes.
> That was my thought. If the comments can be in a lot of places, you have to change the parsing in a lot of places. But if the comments always look the same, it's not so difficult to just "pre-process" the file in such a way that you remove the comments and then give the result to the existing code (that then no longer requires any changes at all).

Well yes this is a valid point. This is actually what we have been doing internally (scripting around the issue)
However, Pointwise is a major mesh generator and I feel it's very weird that our reader just crashes when reading a gmsh file generated by Pointwise. I imagine that a random user will find it extremely difficult to debug that it is because of the COMMENTS sections. I would prefer if the native deal.II reader would support as many type of variants of GMSH files as possible.

The PR by Mikael does exactly that. Instead of assuming that the sections are in a pre-established order that is "hardcoded" he just flags which sections are necessary and automatically discards the useless information that can be comments, but that can be something else also (e.g. other information written by other meshers).

How do you suggest we move ahead @bangerth ? I would prefer that the deal.II GMSH reader just works out of the bat, since otherwise this means scripting around the issue. We could either "double read" the GMSH file to strip it out of comments internally, or use the current by @mivaia which dynamically throws the stuff away by selected the regions that are necessary. I prefer the latter, since I think it will be significantly faster than double "processing" the text, but I'm ok with both.

It appears as a major change, but in reality it is not, it's just a restructure of the current code for it to be more flexible.

2024-09-09 15:52 UTC, bangerth commented
Oh, of course it should just work in deal.II. I was suggesting to do the stripping of comments at the top of the function, putting the rest of the file into a `std::string`, putting the string into an `std::istringstream`, and letting the rest of the function just read from that.

2024-09-09 17:52 UTC, blaisb commented
> Oh, of course it should just work in deal.II. I was suggesting to do the stripping of comments at the top of the function, putting the rest of the file into a `std::string`, putting the string into an `std::istringstream`, and letting the rest of the function just read from that.

Yeah sure, that seems like a good idea.
@mivaia do you think you can give it a go? I'll be glad to help you :)

2024-09-23 17:11 UTC, mivaia commented
Really good idea to just delete the comments at the beginning! I modified my code to implement this. Sorry for the little delay between the modifications.

2024-09-23 19:17 UTC, bangerth approved these changes
Yes, this is excellent!. Thank you!

2024-09-24 19:03 UTC, blaisb requested changes
Just two small things. Very cool work

2024-09-24 19:03 UTC, blaisb commented on source/grid/grid_in.cc
> +  // contain the the file stripped of the comments
```suggestion
  // contain the content of the file stripped of the comments
```

2024-09-24 19:03 UTC, blaisb commented on source/grid/grid_in.cc
> +
```suggestion
  // Restart reading the file normally since it has been stripped of comments
  std::istringstream in(stripped_file);

```

2024-09-26 16:50 UTC, blaisb approved these changes

2024-09-26 16:51 UTC, blaisb commented
/rebuild

2024-09-26 17:23 UTC, bangerth commented
/rebuild

2024-09-27 21:35 UTC, merged