Rename a member of class SmartPointer.
dealii/dealii pull request #17675
Opened 2024-09-06 21:23 UTC by bangerth

This is the follow-up to #17673 and related to #17657. `SmartPointer` has a member variable simply called `t`; just `p` for "pointer" would have been bad enough, but `t` really doesn't give anything away, so this patch renames it to `pointer`.

2024-09-06 23:06 UTC, drwells requested changes
Want to give that exception a better name too?

2024-09-06 23:06 UTC, drwells commented on include/deal.II/base/smartpointer.h
> +             ExcMessage("You can'pointer copy a smart pointer object that "
```suggestion
             ExcMessage("You can't copy a smart pointer object that "
```
:)

2024-09-06 23:06 UTC, drwells commented on include/deal.II/base/smartpointer.h
> +             ExcMessage("You can'pointer copy a smart pointer object that "
```suggestion
             ExcMessage("You can't copy a smart pointer object that "
```

2024-09-06 23:06 UTC, drwells commented on include/deal.II/base/smartpointer.h
> +             ExcMessage("You can'pointer move a smart pointer object that "
```suggestion
             ExcMessage("You can't move a smart pointer object that "
```

2024-09-06 23:06 UTC, drwells commented on include/deal.II/base/smartpointer.h
> +             ExcMessage("You can'pointer copy a smart pointer object that "
```suggestion
             ExcMessage("You can't copy a smart pointer object that "
```

2024-09-07 19:39 UTC, bangerth commented
Wow, eclipse is usually really good at renaming symbols. This one definitely failed...

2024-09-08 12:50 UTC, merged