Rename SmartPointer -> ObserverPointer.
dealii/dealii pull request #17689
Opened 2024-09-11 15:39 UTC by bangerth

As discussed in #17657. The old file, `smartpointer.h`, retains a `using` declaration that continues to make the old class name available. I added a test for that as well.

2024-09-11 17:46 UTC, bangerth commented
Amusingly, my script also renamed `vtkSmartPointer` to `vtkObserverPointer`, which obviously fails. It's funny that other projects also use this rather non-descriptive name. They are also significantly worse than we are at documenting what the class actually does: https://vtk.org/doc/nightly/html/classvtkSmartPointer.html

Either way, I undid the accidental renaming.

2024-09-12 12:38 UTC, kronbichler approved these changes

2024-09-12 13:28 UTC, drwells requested changes
two minor comments

2024-09-12 16:41 UTC, bangerth commented
Updated as requested.

2024-09-12 16:41 UTC, drwells approved these changes
Thanks!

2024-09-12 16:43 UTC, drwells commented on doc/news/3.4.0-vs-4.0.0.h
> +       count how many <code>ObserverPointer</code> objects subscribe
I've gone back and read those and I think the old changelogs (and, unfortunately, the old mailing list archive, which is now unavailable) are pretty interesting as historical documents. I think we should keep them around as-is.

2024-09-12 18:39 UTC, drwells commented
This is a pretty big change - anyone else have an opinion on it?

2024-09-12 18:54 UTC, kronbichler approved these changes

2024-09-17 21:29 UTC, masterleinad approved these changes

2024-09-17 21:29 UTC, merged