check an invariant of class IndexSet
dealii/dealii pull request #17763
Opened 2024-10-09 19:43 UTC by fernandohv3279

2024-10-09 21:12 UTC, bangerth commented
/rebuild

2024-10-09 21:19 UTC, bangerth commented
We practiced writing tests in my research group meeting today. This is the outcome. I would appreciate if someone else took a look.

2024-10-10 01:13 UTC, drwells approved these changes
Nice!

2024-10-10 01:45 UTC, drwells requested changes

2024-10-10 01:45 UTC, drwells commented on tests/base/index_set_empty.output
> +DEAL::OK
```suggestion
```

2024-10-12 21:14 UTC, drwells approved these changes

2024-10-12 21:14 UTC, merged