FunctionFromFunctionObjects: accept single function
dealii/dealii pull request #17780
Opened 2024-10-15 08:44 UTC by peterrum

2024-11-03 20:41 UTC, peterrum commented
Anyone?

2024-11-04 18:53 UTC, bangerth requested changes

2024-11-04 18:53 UTC, bangerth commented on include/deal.II/base/function.h
> +   * of the vector @p values. A call to the FunctionFromFunctionObject::gradient()
This sentence is no longer true. Instead, you are passing the number of components explicitly.

2024-11-04 19:16 UTC, peterrum commented
@bangerth I have made the changes!

2024-11-04 20:00 UTC, bangerth approved these changes

2024-11-04 23:21 UTC, merged