Add the step-93 tutorial program
dealii/dealii pull request #17848
Opened 2024-11-06 22:37 UTC by Sam0h51

This pull request adds the step-93 tutorial program, which shows how to use nonlocal dofs within the existing deal.II framework.

2024-11-06 22:43 UTC, Sam0h51 commented
[The deal.II Library The step-93 tutorial program.pdf](https://github.com/user-attachments/files/17653853/The.deal.II.Library.The.step-93.tutorial.program.pdf)

This is a PDF version of the entire tutorial program for easier reading.

2024-11-06 23:09 UTC, bangerth commented
@dealii/dealii This tutorial grew out of the discussion we had at the user and developer workshop this summer here in Fort Collins. Since there does seem to be a need to support nonlocal DoFs, and since my student @Sam0h51 had a program going in this direction mostly finished already, I asked him whether we could make it into a tutorial program.

The approach chosen here is to allocate these DoFs on a few early cells using the hp framework, and use `FE_Nothing` for the remainder of the cells. We are all in agreement that this is not an "intuitive" approach. It has the benefit that it works with the current system and is teachable with not too much difficulty. 

My personal thoughts on this are:
* It's better to have a tutorial that illustrates how to do something than to not have a tutorial. So this step-93 here is a step forward.
* If we come up with a better approach, we'll change step-93 to use that better approach.

Since @Sam0h51 is my student, I'd appreciate if others could review the program.

2025-01-16 00:41 UTC, bangerth commented
@dealii/dealii Anyone who would be willing to take a look at this program?

2025-01-23 19:29 UTC, cembooks commented
Hello, 

I am working on step-91 tutorial. I have chosen the name “step-91”  for my new shiny tutorial as the last tutorial on dealii.org is step-90. Today I have discovered that there are more tutorials in preparation.  This tutorial, for example, is step-93.  How do I reserve the number for my new shiny tutorial? I guess it must be step-94. Am I right?

2025-01-23 19:33 UTC, peterrum commented
@cembooks https://github.com/dealii/dealii/issues/11998

2025-01-28 03:17 UTC, bangerth commented
Ping? Anyone?

2025-01-28 14:14 UTC, drwells commented
I am a lot freer this semester - I'll take a look this week!

2025-02-05 18:47 UTC, drwells requested changes
This is in pretty good shape - nice work.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/intro.dox
> +is substantial debate on whether we can implement *better* ways to achieve
:)

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/intro.dox
> +for other purposes; if consensus is ever reached on these alternative
"if consensus is ever reached" we need to get back to this one before long - it would be great to have this fixed in time for 9.7.

Fixing that is our (the principal developers') responsibility; it isn't up to this tutorial program.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/intro.dox
> +  DoFTools::count_dofs_per_fe_block() or DoFTools::count_dofs_per_component()
```suggestion
  DoFTools::count_dofs_per_fe_block() or DoFTools::count_dofs_per_fe_component()
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/intro.dox
> +  first four cells.
Do we have any advice for how to make this work in parallel? One possibility would be to check for `global_active_cell_index() < 4`.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/intro.dox
> +the same result that do not require this kind of "abuse" of features intended
We should mention at some point that using `DoFHandler` in hp-mode is more expensive than non-hp mode, so there is a runtime cost to this approach.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +    {}
We should definitely default-initialize `radius`.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +            CircularIndicatorFunction<dim>(Point<dim>({0.5}), 0.2));
```suggestion
          heat_functions.emplace_back(Point<dim>({0.5}), 0.2);
```
etc.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +                    << std::endl;
```suggestion
          DEAL_II_ASSERT_UNREACHABLE();
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +    // problem, and creat 2, 4, or 8 function objects.
```suggestion
    // problem and create 2, 4, or 8 function objects.
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +        if (number_of_c_active_cells >= heat_functions.size())
Here it is! I'd prefer to check with `cell->global_active_cell_index()` so that things automatically work in parallel with this approach.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +    // To get this started, we create a dummy `hp_fe_values` that we
```suggestion
    // To get this started, we create a `hp_fe_values` that we
```
It is a dummy object but sometimes that word trips students up (i.e., they have not heard the phrase "dummy variable" before) - lets just call it what it is.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +    // create a new dummy dof handler to output the target function
Like above - I believe avoiding words like 'dummy' and 'toy' and instead using more ad hoc descriptions makes this easier to understand.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +              << "+" << n_dofs_l << " = " << n_dofs_u + n_dofs_l + n_dofs_c
```suggestion
              << "+" << n_dofs_c << " = " << n_dofs_u + n_dofs_l + n_dofs_c
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/results.dox
> +Number of degrees of freedom: 66049+66049+66049 = 132102
```suggestion
Number of degrees of freedom: 66049+66049+4 = 132102
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/doc/results.dox
> +Solved in 39973 MINRES iterations.
```suggestion
Solved in 39973 MINRES iterations.
```
Can we use a better preconditioner by default, even if it is a very simple one like ILU? I know it is mentioned in possibilities for extension, but students sometimes haphazardly write `PreconditionIdentity` in their own solvers because they saw it in a tutorial program.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +    SolverControl solver_control(1'000'000, 1e-6 * system_rhs.l2_norm());
Nice use of the digit separator!

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +#include <iostream>
We include headers in the tutorial programs in a slightly different order. Can you make sure these are grouped in the same way as, e.g., step-6?

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +#include <deal.II/numerics/matrix_tools.h>
```suggestion
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +#include <deal.II/numerics/smoothness_estimator.h>
```suggestion
```

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +                                   update_quadrature_points);
Could you use the constructor (here and everywhere else) which takes a `MappingCollection` as an argument instead? I'd prefer to avoid implicit mappings so that we can more easily port example programs to simplex meshes.

2025-02-05 18:47 UTC, drwells commented on examples/step-93/step-93.cc
> +                // linear system.
```suggestion
```
I don't think this is worth noting since this is exactly how we handle forcing functions in all Laplace solver examples.

2025-02-18 19:00 UTC, Sam0h51 commented on examples/step-93/step-93.cc
> +            CircularIndicatorFunction<dim>(Point<dim>({0.5}), 0.2));
I'm not quite sure what you are suggesting here. If I take the change as is, I think the code will break because you are replacing a Function object with a (Point, float) tuple. Was this the intention, or does emplace back create a new object as part of the function call?

2025-02-18 19:06 UTC, masterleinad commented on examples/step-93/step-93.cc
> +            CircularIndicatorFunction<dim>(Point<dim>({0.5}), 0.2));
> does emplace back create a new object as part of the function call?

Yes, with `emplace_back` you provide constructor arguments directly.

2025-02-18 20:15 UTC, drwells commented on examples/step-93/doc/intro.dox
> +a node that was clearly part of one cell or another. This was true
Let me know if you need some help writing this one up.

2025-02-19 22:10 UTC, Sam0h51 commented on examples/step-93/step-93.cc
> +        if (number_of_c_active_cells >= heat_functions.size())
I'm also confused by this comment. If I understand correctly, `cell->global_active_cell_index()` returns the global index of the current cell, but what I'm trying to do here is set the active finite element index on each of the first four cells to 1. Should I put the `global_active_cell_index()` above the assignment? Perhaps something like `if(cell->global_active_cell_index() < <desired number of nonlocal dofs>){assign fe index} else break`?

2025-02-20 13:40 UTC, drwells commented on examples/step-93/step-93.cc
> +        if (number_of_c_active_cells >= heat_functions.size())
Yes - that's exactly it.

2025-02-20 20:38 UTC, Sam0h51 commented on examples/step-93/doc/intro.dox
> +a node that was clearly part of one cell or another. This was true
That would be helpful. So far, I've changed the intro to read

>In all previous tutorial programs, we have only ever dealt with
discretizations of partial differential equations posed on a
Triangulation where every degree of freedom was associated with
a local geometric element (vertices, lines, quadrangles, etc.) which
is clearly part of one cell or another (or, in the worst case, some
small number of adjascent cells). This was true
whether we were solving a single differential equation (say, in step-4
or step-6), or a system of coupled equations (step-8, step-22, and
many others).

2025-02-20 20:57 UTC, Sam0h51 commented on examples/step-93/doc/intro.dox
> +where $\lambda$ is a Lagrange multiplier and $(\cdot, \cdot)$ denotes the usual $L^2$ scalar
I've updated the documentation to read

>where $\lambda = \lambda(\mathbf{x})$ is a Lagrange multiplier and $(\cdot, \cdot)$ denotes the usual $L^2$ scalar
product (note that $\lambda$ is a function that lives in the space of test functions, not just a scalar). We do this because finding a critical point of $L$
is equivalent to solving the original optimization problem, and we can find a critical point
of $L$ by finding roots of its derivatives.

Does this seem clear enough?

2025-02-25 17:07 UTC, bangerth commented on examples/step-93/step-93.cc
> +                                   update_quadrature_points);
@Sam0h51 and I talked about this, and decided to keep it simple by not using the mapping argument. I see your point, but at the same time this program is about nonlocal DoFs and not mappings, and it's posed on a square domain. Let's not add something else that needs to be explained.

2025-02-25 17:09 UTC, bangerth commented on examples/step-93/doc/intro.dox
> +the same result that do not require this kind of "abuse" of features intended
Perhaps true, but do you think it makes a difference? In my timings the DoFHandler operations never seem to show up very high on profiles. There is, of course, also the issue that we don't currently have an alternative and it seems not useful to point out that A is more expensive than B if A is your only option.

2025-02-26 20:24 UTC, drwells commented on examples/step-93/doc/intro.dox
> +the same result that do not require this kind of "abuse" of features intended
That's a fair point - lets not add it in here.

2025-03-25 19:14 UTC, drwells commented
Could you rebase, squash, and then fix the indentation problem?

2025-04-08 16:53 UTC, bangerth commented
@Sam0h51 and I played around with preconditioners a bit, and didn't quite get anywhere. There are two issues: (i) Currently, the program uses MinRes, which while being able to solve indefinite problems, wants a definite preconditioner. So it can't use `SparseILU` as a preconditioner. We worked around this by switching to GMRES instead. (ii) `SparseILU` is quite sensitive to the ordering of degrees of freedom because our implementation doesn't do any pivoting. If you get the ordering wrong, you run into a zero pivot and the whole program crashed and burns. Otherwise, things may or may not work and Sam ended up with a situation where the preconditioner must have been singular because the solution he got is wrong. The underlying issue is that ILU is just not a very good preconditioner. A good preconditioner would have to take into account the block structure of the system, but ILU doesn't.

In the end, it's clear that a better solver would benefit the program. At the same time, that's not what *this* program is about. My suggestion therefore is that we keep with what's currently implemented, mostly because it's easy and cheap. Once merged, I will then write a few paragraphs about ideas how one would implement a better linear solver.

Does that sounds acceptable?

2025-04-09 13:32 UTC, drwells commented
I'll do one final readthrough once this is rebased and the history is cleaned up. Do you see how to do that? If not one of us can help.

2025-04-12 00:28 UTC, Sam0h51 commented
Wolfgang and I will work through this. There are a couple places in the history where the main deal.ii branch is merged with the step-93-construction branch (my mistake), so we need to sort that out.

2025-04-15 16:23 UTC, bangerth commented
We rebased and merged all of the commits. I think this is ready for final review and merge.

2025-04-24 19:31 UTC, drwells approved these changes
Looks good.

The images don't load correctly - I think that's a bug on our end since they are all present in the large assets repository.

2025-04-24 19:31 UTC, drwells commented
/rebuild

2025-04-24 21:57 UTC, merged

2025-04-24 21:58 UTC, drwells commented
@Sam0h51 Thanks!

2025-04-25 01:06 UTC, bangerth commented
Yay! Nicely done, @Sam0h51 !