add a tolerance parameter with a default value to match periodic pts.
dealii/dealii pull request #17921
Opened 2024-12-10 08:29 UTC by yjobic

I would like to add a tolerance parameter with a default value to match  periodic points.

2024-12-16 02:46 UTC, drwells requested changes
Nice generalization. I have one minor documentation request.

2024-12-16 02:46 UTC, drwells commented on include/deal.II/grid/grid_tools.h
> +   * the nearest tolerance), if $M\cdot v_1 + offset - v_2$ is parallel to the
Could you update this formula to show exactly how it is related to the new tolerance parameter?

2025-01-01 17:50 UTC, blaisb commented
That's a great addition, especially for meshes coming out of meshing software.

2025-01-01 17:54 UTC, blaisb requested changes
Nice change, but 1-2 comments just to look at.

2025-01-01 17:54 UTC, blaisb commented on include/deal.II/grid/grid_tools.h
> +    const double              tolerance = 1e-10);
I understand that 1e-10 was the previous value of the hardcoded tolerance. I have a quick question, is this value scaled with the "scale" or "length" of the mesh within the code? What I mean by this is that if this is an absolute tolerance or a relative tolerance. I think it would be better to name it specifically as to what it is. Given how it is used below, I think this is an absolute tolerance since it seems to have units of length.

2025-01-06 10:21 UTC, yjobic commented
I made some changes. Thanks for the useful comments.

2025-01-11 21:39 UTC, blaisb approved these changes
This is a great generalization. Thanks. Eventually we might consider making that tolerance relative, but I think it's a bit different from what your PR targets.

2025-01-11 21:39 UTC, blaisb commented
/rebuild

2025-01-12 07:21 UTC, peterrum reviewed
Could you add a test?

2025-03-19 13:49 UTC, yjobic commented
I can add a small test, which is showing how it works (i mean, just how to use the tolerance parameter). Is it enough ?

2025-03-25 19:15 UTC, drwells commented
Maybe Bruno has something else in mind, but in general a simple test is enough.

2025-03-29 16:23 UTC, blaisb commented
Simple test would indeed be more than enough. Do you need help with this @yjobic ?

2025-03-31 07:24 UTC, yjobic commented
I've added the test. Maybe i forgot the add the new source file somewhere in a cmake list. I also run the indent script. I hope it's ok now. Please tell me if it's still missing something. Thanks a lot for the review !

2025-03-31 14:57 UTC, blaisb requested changes
Please find my comments below, I added some suggestions to make the test more relevant.

2025-03-31 14:57 UTC, blaisb commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +        face->set_boundary_id(0);
I am not sure i understand why you are doing it this way. Why not use the other interface in which you provide 2 boundary IDs? This way you would not have to change the boundary ID in this way

2025-03-31 14:57 UTC, blaisb commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  const unsigned int direction = 0; //x-direction
I am not sure this is actually testing your feature. You are providing a tolerance, but that tolerance will not be broken. What I would suggest is to actually shift the nodes of the other boundary by a value of 1e-8. Then try to collect the pairs with a tolerance of 1e-7 or 1e-9 and you will be able to print out both possibilities. This would be a more appropriate test. Right now this is not really testing the feature as far as I understand this.

2025-03-31 16:12 UTC, yjobic commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +        face->set_boundary_id(0);
You're right. It's just that the geometry i'm using has faces not aligned with the i-th periodic direction. Thus the periodic collect with 2 different boundary Ids are not usable for me. For a simpler test, i can erase this part, as an hyper-cube has not this "problem".

2025-03-31 16:15 UTC, yjobic commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  const unsigned int direction = 0; //x-direction
I was kind of afraid of that. I don't know how to slightly move the nodes. I'm kind of new to the dealii community. I'll look into it.

2025-03-31 17:48 UTC, blaisb commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  const unsigned int direction = 0; //x-direction
If you can't figure out and you need help, feel free to reach out to me here and i will be glad to help.

2025-03-31 17:50 UTC, blaisb commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  const unsigned int direction = 0; //x-direction
Something like https://www.dealii.org/current/doxygen/deal.II/namespaceGridTools.html#ac4e8aecd2cf74d3476e0daa11a00248b Could help you to have a cheap solution.

2025-04-01 08:02 UTC, yjobic commented
Many thanks Bruno for your help!! And the time taken to help me (i watched the talk of Wolfgang B. from the award). It's now testing correctly the tolerance parameter. When i'm running the indent script, i still have an error that i don't understand :
<code>Invalid author 'yjobic@gmail.com' without firstname and lastname</code>
Even if it seems ok
<code>git config --global -l
user.email=yjobic@gmail.com
user.name=Yann Jobic
</code>

2025-04-04 12:46 UTC, drwells commented
While the configuration is correct, some of the previous commits have your email address as your name. Can you squash your commits? That should fix the problem.

2025-04-04 12:52 UTC, drwells requested changes

2025-04-04 12:52 UTC, drwells commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  // activate debug to see it fail
This test is most of what you need but we should definitely check that things work correctly (i.e., we can match faces correctly despite some distortion). Checking the failure would be nice but isn't as important.

If you run this test it should generate an output file: can you add that as `grid_tools_collect_periodic_faces_parallel_tolerance.output`?

2025-04-04 12:52 UTC, drwells commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +    periodicity_vector;
Can we use a plain `Triangulation` instead? That way this test would not depend on p4est or MPI.

2025-04-04 12:52 UTC, drwells commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +
Could you add a brief comment here explaining what this test tests?

2025-04-04 13:24 UTC, yjobic commented on tests/grid/grid_tools_collect_periodic_faces_parallel_tolerance.cc
> +  // activate debug to see it fail
I'm using the "deallog" function. That means that there is no output. There is a big fail in debug compilation mode if the function can not find the corresponding periodic nodes. In release, there may not be some fail message (controled by assert)

2025-04-04 14:09 UTC, yjobic commented
I added the comments, and a sequential test. I forgot how to print output values with the dealloc function. If you give me the commands, i'll add the outputs. 
Moreover, if the author git variable is not correct, how can i fix it ? I already pushed it to the PR, it's not local anymore... If it's a problem, otherwise it's ok.

2025-04-04 14:14 UTC, drwells commented
No problem - thanks for continuing to work on this.

1. If you use `mpi_initlog()` or `initlog()` then `deallog` will be set up to create an output file in the right way (basically every test does this). All you have to do is send output to `deallog` and everything else should just work, e.g., `deallog << "Caught the expected exception" << std::endl;` (one quirk of deallog is it needs `std::endl` and not `\n` to correctly end lines).
2. Since we are updating authorship information we need to overwrite the existing commits: that requires force-pushing (via `git push -f`). Can you try doing that after you squash your commits (and verifying author information)?

2025-04-09 15:23 UTC, drwells commented
Since GitHub hides most authorship information I had to check out your branch to see which commits are still causing problems with the indentation script: 7882c1cd78441e4edd90b6bb0142578c3939c869 and dee11b183c216a687a00b936e8ead9563ccb95fc don't have "firstname lastname" authors. Can you either fix those or squash your commits and then force-push?

Since you added the serial version of the test can we get rid of the parallel one?

2025-04-14 08:04 UTC, yjobic commented
Done.

2025-04-14 08:26 UTC, yjobic commented
it should be good now. I learned some git stuff. That's good. I swept a little bit with the rebase, i was afraid to break everything!

2025-04-30 21:35 UTC, masterleinad approved these changes

2025-05-04 17:41 UTC, blaisb commented
@drwells is the current version ok with you?

2025-05-14 23:48 UTC, drwells approved these changes

2025-05-14 23:49 UTC, drwells commented
/rebuild

2025-05-14 23:50 UTC, drwells commented
I think we need to rebase before the CI may be run.

2025-05-30 13:28 UTC, drwells commented
@yjobic can you rebase this PR?

2025-06-02 12:07 UTC, yjobic commented
It should be ok now. I synchronized my fork and rebased the PR.

2025-06-05 14:05 UTC, merged